import { applyKalaoSeed } from "./seed-extra";
import type { CrmStore } from "./types";

const owner = {
  admin: { name: "Super Admin Kalao", image: "avatar-01.jpg" },
  awa: { name: "Awa Koné", image: "avatar-06.jpg" },
  jean: { name: "Jean-Marc Diallo", image: "avatar-13.jpg" },
  fatou: { name: "Fatou N'Diaye", image: "avatar-17.jpg" },
  ibrahim: { name: "Ibrahim Traoré", image: "avatar-14.jpg" },
};

export function createSeedStore(): CrmStore {
  return applyKalaoSeed({
    companies: [
      {
        id: "co-001",
        name: "Société Ivoirienne de Négoce",
        industry: "Commerce",
        website: "https://sin-ci.example",
        phone: "+225 27 20 30 10 01",
        email: "contact@sin-ci.example",
        address: "Boulevard de la République",
        city: "Abidjan",
        country: "Côte d'Ivoire",
        tags: "VIP",
        ownerName: owner.awa.name,
        ownerImage: owner.awa.image,
        image: "company-icon-01.svg",
        status: "active",
      },
      {
        id: "co-002",
        name: "Agro Kalao SARL",
        industry: "Agroalimentaire",
        website: "https://agrokalao.example",
        phone: "+225 27 21 44 20 12",
        email: "hello@agrokalao.example",
        address: "Zone industrielle Yopougon",
        city: "Abidjan",
        country: "Côte d'Ivoire",
        tags: "Collab",
        ownerName: owner.jean.name,
        ownerImage: owner.jean.image,
        image: "company-icon-02.svg",
        status: "active",
      },
      {
        id: "co-003",
        name: "Atlantic Services CI",
        industry: "Services",
        website: "https://atlantic-ci.example",
        phone: "+225 07 08 12 34 56",
        email: "info@atlantic-ci.example",
        address: "Cocody Riviera",
        city: "Abidjan",
        country: "Côte d'Ivoire",
        tags: "Collab",
        ownerName: owner.fatou.name,
        ownerImage: owner.fatou.image,
        image: "company-icon-03.svg",
        status: "active",
      },
      {
        id: "co-004",
        name: "Hôtel Baobab",
        industry: "Hôtellerie",
        website: "https://hotelbaobab.example",
        phone: "+221 33 822 10 20",
        email: "reservation@hotelbaobab.example",
        address: "Corniche Ouest",
        city: "Dakar",
        country: "Sénégal",
        tags: "VIP",
        ownerName: owner.ibrahim.name,
        ownerImage: owner.ibrahim.image,
        image: "company-icon-04.svg",
        status: "active",
      },
      {
        id: "co-005",
        name: "TransAfrique Logistique",
        industry: "Logistique",
        website: "https://transafrique.example",
        phone: "+225 27 22 55 40 18",
        email: "ops@transafrique.example",
        address: "Port autonome",
        city: "Abidjan",
        country: "Côte d'Ivoire",
        tags: "Collab",
        ownerName: owner.awa.name,
        ownerImage: owner.awa.image,
        image: "company-icon-05.svg",
        status: "active",
      },
      {
        id: "co-006",
        name: "Clinique des Palmiers",
        industry: "Santé",
        website: "https://palmiers-sante.example",
        phone: "+225 27 22 41 33 09",
        email: "accueil@palmiers-sante.example",
        address: "Marcory Zone 4",
        city: "Abidjan",
        country: "Côte d'Ivoire",
        tags: "Promotion",
        ownerName: owner.fatou.name,
        ownerImage: owner.fatou.image,
        image: "company-icon-06.svg",
        status: "active",
      },
      {
        id: "co-007",
        name: "Énergie Soleil SA",
        industry: "Énergie",
        website: "https://energiesoleil.example",
        phone: "+226 25 30 12 40",
        email: "projets@energiesoleil.example",
        address: "Ouaga 2000",
        city: "Ouagadougou",
        country: "Burkina Faso",
        tags: "VIP",
        ownerName: owner.jean.name,
        ownerImage: owner.jean.image,
        image: "company-icon-07.svg",
        status: "inactive",
      },
      {
        id: "co-008",
        name: "Boutique Niani",
        industry: "Retail",
        website: "https://niani.example",
        phone: "+223 20 22 18 40",
        email: "boutique@niani.example",
        address: "Avenue de l'Indépendance",
        city: "Bamako",
        country: "Mali",
        tags: "Collab",
        ownerName: owner.ibrahim.name,
        ownerImage: owner.ibrahim.image,
        image: "company-icon-08.svg",
        status: "active",
      },
    ],
    contacts: [
      {
        id: "ct-001",
        companyId: "co-001",
        firstName: "Aminata",
        lastName: "Kouassi",
        email: "a.kouassi@sin-ci.example",
        phone: "+225 07 01 22 33 44",
        jobTitle: "Directrice des achats",
        location: "Abidjan",
        tags: "VIP",
        rating: "4.8",
        image: "avatar-19.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-002",
        companyId: "co-002",
        firstName: "Koffi",
        lastName: "Yao",
        email: "k.yao@agrokalao.example",
        phone: "+225 05 12 44 55 66",
        jobTitle: "Responsable exploitation",
        location: "Abidjan",
        tags: "Collab",
        rating: "4.5",
        image: "avatar-20.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-003",
        companyId: "co-003",
        firstName: "Mariama",
        lastName: "Sow",
        email: "m.sow@atlantic-ci.example",
        phone: "+225 01 23 45 67 89",
        jobTitle: "Chef de projet",
        location: "Abidjan",
        tags: "Collab",
        rating: "4.2",
        image: "avatar-21.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-004",
        companyId: "co-004",
        firstName: "Abdoulaye",
        lastName: "Diop",
        email: "a.diop@hotelbaobab.example",
        phone: "+221 77 123 45 67",
        jobTitle: "Directeur général",
        location: "Dakar",
        tags: "VIP",
        rating: "5",
        image: "avatar-22.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-005",
        companyId: "co-005",
        firstName: "Sandrine",
        lastName: "Mensah",
        email: "s.mensah@transafrique.example",
        phone: "+225 07 88 99 00 11",
        jobTitle: "Responsable logistique",
        location: "Abidjan",
        tags: "Promotion",
        rating: "4.0",
        image: "avatar-23.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-006",
        companyId: "co-006",
        firstName: "Dr. Paul",
        lastName: "Bamba",
        email: "p.bamba@palmiers-sante.example",
        phone: "+225 05 44 33 22 11",
        jobTitle: "Directeur médical",
        location: "Abidjan",
        tags: "Collab",
        rating: "4.6",
        image: "avatar-24.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-007",
        companyId: "co-007",
        firstName: "Salimata",
        lastName: "Ouédraogo",
        email: "s.ouedraogo@energiesoleil.example",
        phone: "+226 70 12 34 56",
        jobTitle: "Ingénieure projets",
        location: "Ouagadougou",
        tags: "VIP",
        rating: "4.3",
        image: "avatar-25.jpg",
        flags: "fr.svg",
        status: "inactive",
      },
      {
        id: "ct-008",
        companyId: "co-008",
        firstName: "Mamadou",
        lastName: "Keita",
        email: "m.keita@niani.example",
        phone: "+223 76 54 32 10",
        jobTitle: "Gérant",
        location: "Bamako",
        tags: "Collab",
        rating: "3.9",
        image: "avatar-26.jpg",
        flags: "fr.svg",
        status: "active",
      },
    ],
    leads: [
      {
        id: "ld-001",
        companyId: "co-001",
        contactId: "ct-001",
        title: "Renouvellement stock négoce T4",
        source: "Salon professionnel",
        status: "qualified",
        estimatedValue: 185000,
        ownerName: owner.awa.name,
        ownerImage: owner.awa.image,
        createdDate: "02 Sep 2026, 10:15",
      },
      {
        id: "ld-002",
        companyId: "co-002",
        contactId: "ct-002",
        title: "Ligne de conditionnement riz",
        source: "Site web",
        status: "contacted",
        estimatedValue: 92000,
        ownerName: owner.jean.name,
        ownerImage: owner.jean.image,
        createdDate: "05 Sep 2026, 14:40",
      },
      {
        id: "ld-003",
        companyId: "co-003",
        contactId: "ct-003",
        title: "Audit organisation commerciale",
        source: "Recommandation",
        status: "new",
        estimatedValue: 24000,
        ownerName: owner.fatou.name,
        ownerImage: owner.fatou.image,
        createdDate: "08 Sep 2026, 09:05",
      },
      {
        id: "ld-004",
        companyId: "co-004",
        contactId: "ct-004",
        title: "Équipement hôtelier + maintenance",
        source: "Appel sortant",
        status: "qualified",
        estimatedValue: 156000,
        ownerName: owner.ibrahim.name,
        ownerImage: owner.ibrahim.image,
        createdDate: "10 Sep 2026, 16:22",
      },
      {
        id: "ld-005",
        companyId: "co-005",
        contactId: "ct-005",
        title: "Prestations logistiques portuaires",
        source: "Partenaire",
        status: "converted",
        estimatedValue: 78000,
        ownerName: owner.awa.name,
        ownerImage: owner.awa.image,
        createdDate: "12 Sep 2026, 11:30",
      },
      {
        id: "ld-006",
        companyId: "co-006",
        contactId: "ct-006",
        title: "Contrats de service clinique",
        source: "E-mail",
        status: "contacted",
        estimatedValue: 41000,
        ownerName: owner.fatou.name,
        ownerImage: owner.fatou.image,
        createdDate: "14 Sep 2026, 08:50",
      },
      {
        id: "ld-007",
        companyId: "co-007",
        contactId: "ct-007",
        title: "Kit solaire 50 kW",
        source: "Salon professionnel",
        status: "unqualified",
        estimatedValue: 210000,
        ownerName: owner.jean.name,
        ownerImage: owner.jean.image,
        createdDate: "15 Sep 2026, 13:10",
      },
      {
        id: "ld-008",
        companyId: "co-008",
        contactId: "ct-008",
        title: "Uniformes et signalétique boutique",
        source: "Site web",
        status: "new",
        estimatedValue: 12500,
        ownerName: owner.ibrahim.name,
        ownerImage: owner.ibrahim.image,
        createdDate: "17 Sep 2026, 15:00",
      },
    ],
    deals: [
      {
        id: "dl-001",
        title: "Pack négoce + formation",
        companyId: "co-001",
        contactId: "ct-001",
        leadId: "ld-001",
        stage: "Negotiation",
        amount: 185000,
        tags: "VIP",
        probability: 80,
        expectedCloseDate: "30 Sep 2026",
        status: "Open",
      },
      {
        id: "dl-002",
        title: "Conditionneuse Agro Kalao",
        companyId: "co-002",
        contactId: "ct-002",
        leadId: "ld-002",
        stage: "Proposal Made",
        amount: 92000,
        tags: "Collab",
        probability: 55,
        expectedCloseDate: "12 Oct 2026",
        status: "Open",
      },
      {
        id: "dl-003",
        title: "Audit Atlantic Services",
        companyId: "co-003",
        contactId: "ct-003",
        leadId: "ld-003",
        stage: "Qualify To Buy",
        amount: 24000,
        tags: "Rated",
        probability: 40,
        expectedCloseDate: "20 Oct 2026",
        status: "Open",
      },
      {
        id: "dl-004",
        title: "Hôtel Baobab — équipement",
        companyId: "co-004",
        contactId: "ct-004",
        leadId: "ld-004",
        stage: "Negotiation",
        amount: 156000,
        tags: "VIP",
        probability: 70,
        expectedCloseDate: "05 Oct 2026",
        status: "Open",
      },
      {
        id: "dl-005",
        title: "Contrat logistique TransAfrique",
        companyId: "co-005",
        contactId: "ct-005",
        leadId: "ld-005",
        stage: "Closed Won",
        amount: 78000,
        tags: "Collab",
        probability: 100,
        expectedCloseDate: "18 Sep 2026",
        status: "Won",
      },
      {
        id: "dl-006",
        title: "Maintenance Clinique des Palmiers",
        companyId: "co-006",
        contactId: "ct-006",
        leadId: "ld-006",
        stage: "Contact Made",
        amount: 41000,
        tags: "Promotion",
        probability: 35,
        expectedCloseDate: "28 Oct 2026",
        status: "Open",
      },
      {
        id: "dl-007",
        title: "Centrale solaire 50 kW",
        companyId: "co-007",
        contactId: "ct-007",
        leadId: "ld-007",
        stage: "Closed Lost",
        amount: 210000,
        tags: "Rejected",
        probability: 0,
        expectedCloseDate: "15 Sep 2026",
        status: "Lost",
      },
      {
        id: "dl-008",
        title: "Identité visuelle Boutique Niani",
        companyId: "co-008",
        contactId: "ct-008",
        leadId: "ld-008",
        stage: "Qualify To Buy",
        amount: 12500,
        tags: "Collab",
        probability: 60,
        expectedCloseDate: "08 Oct 2026",
        status: "Open",
      },
    ],
    catalog: [
      {
        id: "ca-001",
        kind: "product",
        name: "Groupe électrogène 10 kVA",
        sku: "PRD-GEN-10",
        description: "Groupe électrogène diesel pour sites tertiaires.",
        category: "Équipement",
        unitPrice: 2850,
        taxRate: 18,
        status: "active",
        unit: "unité",
        billingType: null,
      },
      {
        id: "ca-002",
        kind: "product",
        name: "Palette riz 25 kg (50 sacs)",
        sku: "PRD-RIZ-25",
        description: "Palette de riz parfumé pour revente.",
        category: "Négoce",
        unitPrice: 980,
        taxRate: 18,
        status: "active",
        unit: "palette",
        billingType: null,
      },
      {
        id: "ca-003",
        kind: "product",
        name: "Uniformes entreprise (lot 20)",
        sku: "PRD-UNI-20",
        description: "Tenues professionnelles brodées Groupe Kalao.",
        category: "Textile",
        unitPrice: 420,
        taxRate: 18,
        status: "active",
        unit: "lot",
        billingType: null,
      },
      {
        id: "ca-004",
        kind: "product",
        name: "Imprimante thermique caisse",
        sku: "PRD-IMP-TH",
        description: "Imprimante tickets pour points de vente.",
        category: "Matériel",
        unitPrice: 185,
        taxRate: 18,
        status: "active",
        unit: "unité",
        billingType: null,
      },
      {
        id: "ca-005",
        kind: "product",
        name: "Panneau solaire 550 W",
        sku: "PRD-SOL-550",
        description: "Module photovoltaïque monocristallin.",
        category: "Énergie",
        unitPrice: 145,
        taxRate: 18,
        status: "active",
        unit: "unité",
        billingType: null,
      },
      {
        id: "ca-006",
        kind: "service",
        name: "Installation et mise en service",
        sku: "SRV-INST-01",
        description: "Pose, tests et formation utilisateurs.",
        category: "Prestations",
        unitPrice: 650,
        taxRate: 18,
        status: "active",
        unit: "forfait",
        billingType: "one_time",
      },
      {
        id: "ca-007",
        kind: "service",
        name: "Contrat de maintenance annuel",
        sku: "SRV-MAINT-12",
        description: "Visites préventives et assistance prioritaire.",
        category: "Prestations",
        unitPrice: 2400,
        taxRate: 18,
        status: "active",
        unit: "an",
        billingType: "yearly",
      },
      {
        id: "ca-008",
        kind: "service",
        name: "Formation équipes commerciales",
        sku: "SRV-FORM-COM",
        description: "Atelier de 2 jours sur le process de vente Kalao.",
        category: "Formation",
        unitPrice: 890,
        taxRate: 18,
        status: "active",
        unit: "session",
        billingType: "one_time",
      },
      {
        id: "ca-009",
        kind: "service",
        name: "Audit organisationnel",
        sku: "SRV-AUDIT-01",
        description: "Diagnostic commercial et plan d'actions 90 jours.",
        category: "Conseil",
        unitPrice: 1800,
        taxRate: 18,
        status: "active",
        unit: "forfait",
        billingType: "one_time",
      },
      {
        id: "ca-010",
        kind: "service",
        name: "Prestation logistique portuaire",
        sku: "SRV-LOG-PORT",
        description: "Manutention, stockage temporaire et acheminement.",
        category: "Logistique",
        unitPrice: 320,
        taxRate: 18,
        status: "active",
        unit: "jour",
        billingType: "daily",
      },
    ],
    quotes: [
      {
        id: "qt-001",
        number: "DEV-2026-001",
        companyId: "co-001",
        quoteDate: "04 Sep 2026",
        validTill: "04 Oct 2026",
        totalAmount: 198000,
        discount: "8%",
        finalAmount: 182160,
        status: "sent",
      },
      {
        id: "qt-002",
        number: "DEV-2026-002",
        companyId: "co-002",
        quoteDate: "07 Sep 2026",
        validTill: "07 Oct 2026",
        totalAmount: 98000,
        discount: "5%",
        finalAmount: 93100,
        status: "draft",
      },
      {
        id: "qt-003",
        number: "DEV-2026-003",
        companyId: "co-004",
        quoteDate: "11 Sep 2026",
        validTill: "11 Oct 2026",
        totalAmount: 168000,
        discount: "10%",
        finalAmount: 151200,
        status: "sent",
      },
      {
        id: "qt-004",
        number: "DEV-2026-004",
        companyId: "co-005",
        quoteDate: "12 Sep 2026",
        validTill: "12 Oct 2026",
        totalAmount: 78000,
        discount: "0%",
        finalAmount: 78000,
        status: "accepted",
      },
      {
        id: "qt-005",
        number: "DEV-2026-005",
        companyId: "co-006",
        quoteDate: "15 Sep 2026",
        validTill: "15 Oct 2026",
        totalAmount: 43000,
        discount: "5%",
        finalAmount: 40850,
        status: "sent",
      },
      {
        id: "qt-006",
        number: "DEV-2026-006",
        companyId: "co-008",
        quoteDate: "17 Sep 2026",
        validTill: "17 Oct 2026",
        totalAmount: 13800,
        discount: "10%",
        finalAmount: 12420,
        status: "draft",
      },
    ],
    invoices: [
      {
        id: "in-001",
        number: "FAC-2026-001",
        companyId: "co-005",
        project: "Contrat logistique",
        projectImage: "project-01.svg",
        dueDate: "30 Sep 2026",
        amount: 78000,
        paidAmount: 78000,
        status: "Paid",
      },
      {
        id: "in-002",
        number: "FAC-2026-002",
        companyId: "co-001",
        project: "Acompte négoce",
        projectImage: "project-02.svg",
        dueDate: "10 Oct 2026",
        amount: 91080,
        paidAmount: 45000,
        status: "Partially Paid",
      },
      {
        id: "in-003",
        number: "FAC-2026-003",
        companyId: "co-003",
        project: "Audit commercial",
        projectImage: "project-03.svg",
        dueDate: "05 Oct 2026",
        amount: 24000,
        paidAmount: 0,
        status: "Unpaid",
      },
      {
        id: "in-004",
        number: "FAC-2026-004",
        companyId: "co-004",
        project: "Équipement hôtel",
        projectImage: "project-04.svg",
        dueDate: "01 Sep 2026",
        amount: 52000,
        paidAmount: 0,
        status: "Overdue",
      },
      {
        id: "in-005",
        number: "FAC-2026-005",
        companyId: "co-006",
        project: "Maintenance clinique",
        projectImage: "project-05.svg",
        dueDate: "20 Oct 2026",
        amount: 2400,
        paidAmount: 2400,
        status: "Paid",
      },
      {
        id: "in-006",
        number: "FAC-2026-006",
        companyId: "co-002",
        project: "Conditionnement",
        projectImage: "project-06.svg",
        dueDate: "18 Oct 2026",
        amount: 46550,
        paidAmount: 20000,
        status: "Partially Paid",
      },
    ],
    activities: [
      {
        id: "ac-001",
        type: "call",
        subject: "Appel de qualification — SIN",
        companyId: "co-001",
        contactId: "ct-001",
        dealId: "dl-001",
        dueAt: "18 Sep 2026 09:30",
        notes: "Confirmer volumes T4 et délai de livraison.",
      },
      {
        id: "ac-002",
        type: "meeting",
        subject: "Visite site Agro Kalao",
        companyId: "co-002",
        contactId: "ct-002",
        dealId: "dl-002",
        dueAt: "19 Sep 2026 14:00",
        notes: "Présenter la conditionneuse et le contrat de maintenance.",
      },
      {
        id: "ac-003",
        type: "email",
        subject: "Envoi devis Hôtel Baobab",
        companyId: "co-004",
        contactId: "ct-004",
        dealId: "dl-004",
        dueAt: "18 Sep 2026 16:00",
        notes: "Joindre fiche produits et planning d'installation.",
      },
      {
        id: "ac-004",
        type: "task",
        subject: "Relance facture Hôtel Baobab",
        companyId: "co-004",
        contactId: "ct-004",
        dealId: "dl-004",
        dueAt: "20 Sep 2026 11:00",
        notes: "Facture FAC-2026-004 en retard.",
      },
      {
        id: "ac-005",
        type: "note",
        subject: "Contrat TransAfrique signé",
        companyId: "co-005",
        contactId: "ct-005",
        dealId: "dl-005",
        dueAt: "18 Sep 2026 08:00",
        notes: "Affaire gagnée, lancement opérationnel semaine 39.",
      },
      {
        id: "ac-006",
        type: "call",
        subject: "Premier contact Boutique Niani",
        companyId: "co-008",
        contactId: "ct-008",
        dealId: "dl-008",
        dueAt: "19 Sep 2026 10:15",
        notes: "Besoin uniformes + signalétique vitrine.",
      },
    ],
    departments: [],
    travel: [],
    immigration: [],
    events: [],
    plantations: [],
    sites: [],
    siteEquipment: [],
    siteAssignments: [],
    siteMilestones: [],
    properties: [],
    payroll: [],
    eventLines: [],
    leases: [],
    payments: [],
    attachments: [],
  });
}
