import type { CrmStore } from "./types";

export function applyKalaoSeed(store: CrmStore): CrmStore {
  return {
    ...store,
    companies: [
      ...store.companies,
      {
        id: "co-101",
        name: "Bâtir Ensemble SARL",
        industry: "BTP",
        website: "https://batir-ensemble.example",
        phone: "+225 27 22 18 40 10",
        email: "chantier@batir-ensemble.example",
        address: "Yopougon Sicogi",
        city: "Abidjan",
        country: "Côte d'Ivoire",
        tags: "BTP",
        ownerName: "Jean-Marc Diallo",
        ownerImage: "avatar-13.jpg",
        image: "company-icon-09.svg",
        status: "active",
      },
      {
        id: "co-102",
        name: "Foncier Lagune",
        industry: "Immobilier",
        website: "https://foncier-lagune.example",
        phone: "+225 07 11 22 33 00",
        email: "biens@foncier-lagune.example",
        address: "Cocody Angré",
        city: "Abidjan",
        country: "Côte d'Ivoire",
        tags: "VIP",
        ownerName: "Fatou N'Diaye",
        ownerImage: "avatar-17.jpg",
        image: "company-icon-10.svg",
        status: "active",
      },
      {
        id: "co-103",
        name: "Plantation N'Zi",
        industry: "Agriculture",
        website: "https://plantation-nzi.example",
        phone: "+225 05 66 77 88 99",
        email: "ferme@plantation-nzi.example",
        address: "Route de Dimbokro",
        city: "Dimbokro",
        country: "Côte d'Ivoire",
        tags: "Collab",
        ownerName: "Ibrahim Traoré",
        ownerImage: "avatar-14.jpg",
        image: "company-icon-11.svg",
        status: "active",
      },
    ],
    contacts: [
      ...store.contacts,
      {
        id: "ct-101",
        companyId: "",
        firstName: "Fatou",
        lastName: "Bamba",
        email: "fatou.bamba@example.com",
        phone: "+225 07 55 10 20 30",
        jobTitle: "Particulier",
        location: "Abidjan",
        tags: "Voyage",
        rating: "4.7",
        image: "avatar-19.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-102",
        companyId: "",
        firstName: "Moussa",
        lastName: "Coulibaly",
        email: "moussa.coulibaly@example.com",
        phone: "+223 76 11 22 33",
        jobTitle: "Particulier",
        location: "Bamako",
        tags: "Immigration",
        rating: "4.4",
        image: "avatar-20.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-103",
        companyId: "",
        firstName: "Aïcha",
        lastName: "Traoré",
        email: "aicha.traore@example.com",
        phone: "+225 05 44 11 22 33",
        jobTitle: "Particulier",
        location: "Bouaké",
        tags: "Événement",
        rating: "4.9",
        image: "avatar-21.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-104",
        companyId: "",
        firstName: "Jean",
        lastName: "Koffi",
        email: "jean.koffi@example.com",
        phone: "+225 01 88 77 66 55",
        jobTitle: "Particulier",
        location: "Abidjan",
        tags: "Immobilier",
        rating: "4.1",
        image: "avatar-24.jpg",
        flags: "fr.svg",
        status: "active",
      },
    ],
    catalog: [
      ...store.catalog,
      {
        id: "ca-101",
        kind: "service",
        name: "Forfait voyage Abidjan–Paris (A/R)",
        sku: "VOY-ABJ-CDG",
        description: "Billet + assistance aéroport",
        category: "Voyages",
        unitPrice: 780,
        taxRate: 18,
        status: "active",
        unit: "personne",
        billingType: "one_time",
      },
      {
        id: "ca-102",
        kind: "service",
        name: "Dossier visa Schengen",
        sku: "IMM-VIS-SCH",
        description: "Assistance complète dossier visa",
        category: "Immigration",
        unitPrice: 450,
        taxRate: 18,
        status: "active",
        unit: "dossier",
        billingType: "one_time",
      },
      {
        id: "ca-103",
        kind: "service",
        name: "Couverture photo mariage",
        sku: "EVT-PHO-01",
        description: "Photographe + album numérique",
        category: "Événementiel",
        unitPrice: 350,
        taxRate: 18,
        status: "active",
        unit: "forfait",
        billingType: "one_time",
      },
      {
        id: "ca-104",
        kind: "service",
        name: "Location chapiteau 200 places",
        sku: "EVT-CHAP-200",
        description: "Montage, démontage, transport",
        category: "Événementiel",
        unitPrice: 620,
        taxRate: 18,
        status: "active",
        unit: "jour",
        billingType: "daily",
      },
      {
        id: "ca-105",
        kind: "service",
        name: "Sono + DJ soirée",
        sku: "EVT-SONO-DJ",
        description: "Régie son et animation",
        category: "Événementiel",
        unitPrice: 280,
        taxRate: 18,
        status: "active",
        unit: "soirée",
        billingType: "one_time",
      },
      {
        id: "ca-106",
        kind: "product",
        name: "Engrais NPK 50 kg",
        sku: "AGR-NPK-50",
        description: "Intrant plantation",
        category: "Agriculture",
        unitPrice: 32,
        taxRate: 18,
        status: "active",
        unit: "sac",
        billingType: null,
      },
      {
        id: "ca-107",
        kind: "product",
        name: "Ciment 50 kg",
        sku: "BTP-CIM-50",
        description: "Matériau de construction",
        category: "BTP",
        unitPrice: 9.5,
        taxRate: 18,
        status: "active",
        unit: "sac",
        billingType: null,
      },
      {
        id: "ca-108",
        kind: "service",
        name: "Gestion locative mensuelle",
        sku: "IMO-GEST-M",
        description: "Suivi loyer et charges",
        category: "Immobilier",
        unitPrice: 85,
        taxRate: 18,
        status: "active",
        unit: "mois",
        billingType: "monthly",
      },
    ],
    departments: [
      { id: "dp-01", code: "DEP-VOY", name: "Voyages", headName: "Awa Koné", headImage: "assets/img/profiles/avatar-06.jpg", membersCount: "6 membres", location: "Abidjan", status: "active" },
      { id: "dp-02", code: "DEP-IMM", name: "Immigration", headName: "Fatou N'Diaye", headImage: "assets/img/profiles/avatar-17.jpg", membersCount: "4 membres", location: "Abidjan", status: "active" },
      { id: "dp-03", code: "DEP-COM", name: "Commerce", headName: "Jean-Marc Diallo", headImage: "assets/img/profiles/avatar-13.jpg", membersCount: "8 membres", location: "Abidjan", status: "active" },
      { id: "dp-04", code: "DEP-PRE", name: "Prestations", headName: "Ibrahim Traoré", headImage: "assets/img/profiles/avatar-14.jpg", membersCount: "5 membres", location: "Abidjan", status: "active" },
      { id: "dp-05", code: "DEP-EVE", name: "Événementiel", headName: "Awa Koné", headImage: "assets/img/profiles/avatar-06.jpg", membersCount: "7 membres", location: "Abidjan", status: "active" },
      { id: "dp-06", code: "DEP-AGR", name: "Agriculture", headName: "Ibrahim Traoré", headImage: "assets/img/profiles/avatar-14.jpg", membersCount: "9 membres", location: "Dimbokro", status: "active" },
      { id: "dp-07", code: "DEP-BTP", name: "BTP", headName: "Jean-Marc Diallo", headImage: "assets/img/profiles/avatar-13.jpg", membersCount: "12 membres", location: "Abidjan", status: "active" },
      { id: "dp-08", code: "DEP-IMO", name: "Immobilier", headName: "Fatou N'Diaye", headImage: "assets/img/profiles/avatar-17.jpg", membersCount: "4 membres", location: "Abidjan", status: "active" },
      { id: "dp-09", code: "DEP-RH", name: "RH", headName: "Super Admin Kalao", headImage: "assets/img/profiles/avatar-01.jpg", membersCount: "3 membres", location: "Abidjan", status: "active" },
      { id: "dp-10", code: "DEP-FIN", name: "Finance", headName: "Super Admin Kalao", headImage: "assets/img/profiles/avatar-01.jpg", membersCount: "3 membres", location: "Abidjan", status: "active" },
      { id: "dp-11", code: "DEP-DIR", name: "Direction", headName: "Super Admin Kalao", headImage: "assets/img/profiles/avatar-01.jpg", membersCount: "2 membres", location: "Abidjan", status: "active" },
    ],
    travel: [
      { id: "tr-001", number: "VOY-2026-014", accountName: "Fatou Bamba", accountType: "individual", destination: "Paris (CDG)", departureDate: "03 Oct 2026", returnDate: "18 Oct 2026", pax: 2, itinerary: "ABJ → CDG, hôtel 14 nuits", status: "Confirmé", amount: 780 },
      { id: "tr-002", number: "VOY-2026-015", accountName: "Société Ivoirienne de Négoce", accountType: "company", destination: "Dubaï", departureDate: "12 Oct 2026", returnDate: "19 Oct 2026", pax: 3, itinerary: "ABJ → DXB, salon affaires", status: "Devis", amount: 2140 },
      { id: "tr-003", number: "VOY-2026-016", accountName: "Moussa Coulibaly", accountType: "individual", destination: "Dakar", departureDate: "22 Sep 2026", returnDate: "28 Sep 2026", pax: 1, itinerary: "ABJ → DSS aller-retour", status: "En cours", amount: 320 },
    ],
    immigration: [
      { id: "im-001", number: "IMM-2026-008", accountName: "Moussa Coulibaly", accountType: "individual", procedure: "Visa Schengen études", country: "France", step: "Pièces", status: "Pièces en cours", dueDate: "30 Sep 2026" },
      { id: "im-002", number: "IMM-2026-009", accountName: "Fatou Bamba", accountType: "individual", procedure: "Regroupement familial", country: "Canada", step: "Dépôt", status: "Dépôt prévu", dueDate: "15 Oct 2026" },
      { id: "im-003", number: "IMM-2026-010", accountName: "Atlantic Services CI", accountType: "company", procedure: "Détachement salarié", country: "Maroc", step: "Visa obtenu", status: "Validé", dueDate: "01 Nov 2026" },
    ],
    events: [
      { id: "ev-001", number: "EVT-2026-021", title: "Mariage Aïcha Traoré", accountName: "Aïcha Traoré", accountType: "individual", eventDate: "25 Oct 2026", services: "Photo, chapiteau, sono", status: "Confirmé", amount: 1250 },
      { id: "ev-002", number: "EVT-2026-022", title: "Lancement Boutique Niani", accountName: "Boutique Niani", accountType: "company", eventDate: "08 Oct 2026", services: "Sono, photo", status: "Préparation", amount: 630 },
      { id: "ev-003", number: "EVT-2026-023", title: "Soirée Hôtel Baobab", accountName: "Hôtel Baobab", accountType: "company", eventDate: "31 Dec 2026", services: "Sono, DJ, éclairage", status: "Devis", amount: 890 },
    ],
    plantations: [
      { id: "pl-001", name: "Bloc cacao N'Zi Nord", crop: "Cacao", location: "Dimbokro", hectares: "42 ha", season: "2026", status: "En production" },
      { id: "pl-002", name: "Palmeraie Comoé", crop: "Palmier à huile", location: "Aboisso", hectares: "18 ha", season: "2026", status: "Entretien" },
      { id: "pl-003", name: "Riziculture Yamoussoukro", crop: "Riz", location: "Yamoussoukro", hectares: "9 ha", season: "2026", status: "Semis" },
    ],
    sites: [
      { id: "st-001", number: "CHT-2026-01", name: "Villa Cocody Angré", accountName: "Jean Koffi", accountType: "individual", location: "Cocody Angré, Abidjan", phase: "Gros œuvre", progress: "45%", manager: "Jean-Marc Diallo", startDate: "02 Jun 2026", endDate: "30 Nov 2026", teamSize: "8", status: "En cours", amount: 68000 },
      { id: "st-002", number: "CHT-2026-02", name: "Entrepôt Port-Bouët", accountName: "Bâtir Ensemble SARL", accountType: "company", location: "Zone portuaire, Abidjan", phase: "Fondations", progress: "20%", manager: "Seydou Konaté", startDate: "18 Aug 2026", endDate: "15 Mar 2027", teamSize: "14", status: "Fondations", amount: 145000 },
      { id: "st-003", number: "CHT-2026-03", name: "Réhabilitation clinique", accountName: "Clinique des Palmiers", accountType: "company", location: "Marcory, Abidjan", phase: "Finitions", progress: "70%", manager: "Aminata Touré", startDate: "10 Mar 2026", endDate: "20 Oct 2026", teamSize: "6", status: "Finitions", amount: 42000 },
    ],
    siteEquipment: [
      { id: "eq-001", code: "ENG-PEL-01", name: "Pelleteuse CAT 320", kind: "Engin", siteName: "Entrepôt Port-Bouët", quantity: "1", condition: "Bon état", status: "En service" },
      { id: "eq-002", code: "ENG-BET-02", name: "Bétonnière 350 L", kind: "Engin", siteName: "Villa Cocody Angré", quantity: "2", condition: "Bon état", status: "En service" },
      { id: "eq-003", code: "ENG-COM-03", name: "Compacteur à plaque", kind: "Engin", siteName: "Entrepôt Port-Bouët", quantity: "1", condition: "À réviser", status: "Maintenance" },
      { id: "eq-004", code: "OUT-ECH-01", name: "Échafaudage 12 m", kind: "Outil", siteName: "Réhabilitation clinique", quantity: "4", condition: "Bon état", status: "En service" },
      { id: "eq-005", code: "OUT-MPQ-02", name: "Marteau-piqueur", kind: "Outil", siteName: "Villa Cocody Angré", quantity: "3", condition: "Usé", status: "Disponible" },
      { id: "eq-006", code: "OUT-LAS-03", name: "Niveau laser", kind: "Outil", siteName: "Réhabilitation clinique", quantity: "2", condition: "Neuf", status: "En service" },
      { id: "eq-007", code: "STK-CIM-50", name: "Ciment 50 kg", kind: "Stock", siteName: "Entrepôt Port-Bouët", quantity: "80 sacs", condition: "Sec", status: "En stock" },
      { id: "eq-008", code: "STK-FER-12", name: "Fer à béton 12 mm", kind: "Stock", siteName: "Villa Cocody Angré", quantity: "1,2 t", condition: "Conforme", status: "En stock" },
    ],
    siteAssignments: [
      { id: "as-001", employee: "Jean-Marc Diallo", role: "Chef de chantier", siteName: "Villa Cocody Angré", startDate: "02 Jun 2026", endDate: "30 Nov 2026", attendance: "Présent", status: "Affecté" },
      { id: "as-002", employee: "Kouadio Yao", role: "Maçon", siteName: "Villa Cocody Angré", startDate: "10 Jun 2026", endDate: "30 Nov 2026", attendance: "Présent", status: "Affecté" },
      { id: "as-003", employee: "Mariam Cissé", role: "Manœuvre", siteName: "Villa Cocody Angré", startDate: "15 Jun 2026", endDate: "30 Sep 2026", attendance: "Congé", status: "Affecté" },
      { id: "as-004", employee: "Seydou Konaté", role: "Conducteur d’engins", siteName: "Entrepôt Port-Bouët", startDate: "18 Aug 2026", endDate: "15 Mar 2027", attendance: "Présent", status: "Affecté" },
      { id: "as-005", employee: "Issa Bamba", role: "Ferrailleur", siteName: "Entrepôt Port-Bouët", startDate: "20 Aug 2026", endDate: "31 Dec 2026", attendance: "Présent", status: "Affecté" },
      { id: "as-006", employee: "Aminata Touré", role: "Cheffe de chantier", siteName: "Réhabilitation clinique", startDate: "10 Mar 2026", endDate: "20 Oct 2026", attendance: "Présent", status: "Affecté" },
      { id: "as-007", employee: "Paul N'Guessan", role: "Électricien", siteName: "Réhabilitation clinique", startDate: "01 Aug 2026", endDate: "20 Oct 2026", attendance: "Absent", status: "Affecté" },
    ],
    siteMilestones: [
      { id: "ms-001", siteName: "Villa Cocody Angré", phase: "Terrassement", progress: "100%", recordedAt: "20 Jun 2026", note: "Fouilles validées", status: "Terminé" },
      { id: "ms-002", siteName: "Villa Cocody Angré", phase: "Fondations", progress: "100%", recordedAt: "15 Jul 2026", note: "Semelles coulées", status: "Terminé" },
      { id: "ms-003", siteName: "Villa Cocody Angré", phase: "Gros œuvre", progress: "45%", recordedAt: "12 Sep 2026", note: "R+1 en cours", status: "En cours" },
      { id: "ms-004", siteName: "Entrepôt Port-Bouët", phase: "Terrassement", progress: "100%", recordedAt: "05 Sep 2026", note: "Plateforme compactée", status: "Terminé" },
      { id: "ms-005", siteName: "Entrepôt Port-Bouët", phase: "Fondations", progress: "20%", recordedAt: "18 Sep 2026", note: "Pieux en cours", status: "En cours" },
      { id: "ms-006", siteName: "Réhabilitation clinique", phase: "Gros œuvre", progress: "100%", recordedAt: "30 Jun 2026", note: "Structure reprise", status: "Terminé" },
      { id: "ms-007", siteName: "Réhabilitation clinique", phase: "Second œuvre", progress: "90%", recordedAt: "28 Aug 2026", note: "Cloisons posées", status: "Terminé" },
      { id: "ms-008", siteName: "Réhabilitation clinique", phase: "Finitions", progress: "70%", recordedAt: "15 Sep 2026", note: "Peinture et carrelage", status: "En cours" },
    ],
    properties: [
      { id: "pr-001", name: "Appartement 3 pièces Plateau", kind: "Location", location: "Abidjan", accountName: "Jean Koffi", accountType: "individual", rent: 350, status: "Occupé" },
      { id: "pr-002", name: "Villa F4 Riviera", kind: "Location", location: "Abidjan", accountName: "Foncier Lagune", accountType: "company", rent: 920, status: "Libre" },
      { id: "pr-003", name: "Immeuble bureaux Marcory", kind: "Gestion", location: "Abidjan", accountName: "Foncier Lagune", accountType: "company", rent: 2400, status: "Occupé" },
    ],
    payroll: [
      { id: "py-001", employee: "Awa Koné", department: "Voyages", period: "Sep 2026", salary: 850, bonus: 120, status: "Payé" },
      { id: "py-002", employee: "Jean-Marc Diallo", department: "BTP", period: "Sep 2026", salary: 920, bonus: 80, status: "Payé" },
      { id: "py-003", employee: "Fatou N'Diaye", department: "Immigration", period: "Sep 2026", salary: 780, bonus: 150, status: "À verser" },
      { id: "py-004", employee: "Ibrahim Traoré", department: "Agriculture", period: "Sep 2026", salary: 760, bonus: 60, status: "À verser" },
    ],
    eventLines: [
      { id: "el-001", eventId: "ev-001", eventNumber: "EVT-2026-021", label: "Photo", quantity: 1, unitPrice: 400 },
      { id: "el-002", eventId: "ev-001", eventNumber: "EVT-2026-021", label: "Chapiteau", quantity: 1, unitPrice: 500 },
      { id: "el-003", eventId: "ev-001", eventNumber: "EVT-2026-021", label: "Sono", quantity: 1, unitPrice: 350 },
      { id: "el-004", eventId: "ev-002", eventNumber: "EVT-2026-022", label: "Sono", quantity: 1, unitPrice: 350 },
      { id: "el-005", eventId: "ev-002", eventNumber: "EVT-2026-022", label: "Photo", quantity: 1, unitPrice: 280 },
      { id: "el-006", eventId: "ev-003", eventNumber: "EVT-2026-023", label: "DJ + éclairage", quantity: 1, unitPrice: 890 },
    ],
    leases: [
      { id: "ls-001", propertyName: "Appartement 3 pièces Plateau", tenant: "Jean Koffi", startDate: "01 Jan 2026", endDate: "31 Dec 2026", rent: 350, status: "Actif" },
      { id: "ls-002", propertyName: "Immeuble bureaux Marcory", tenant: "Foncier Lagune", startDate: "01 Mar 2026", endDate: "28 Feb 2028", rent: 2400, status: "Actif" },
      { id: "ls-003", propertyName: "Villa F4 Riviera", tenant: "—", startDate: "", endDate: "", rent: 920, status: "Libre" },
    ],
    payments: [
      { id: "pm-001", invoiceNumber: "FAC-2026-001", amount: 78000, method: "Virement", paidAt: "12 Sep 2026", status: "Validé" },
      { id: "pm-002", invoiceNumber: "FAC-2026-002", amount: 45000, method: "Chèque", paidAt: "15 Sep 2026", status: "Validé" },
    ],
  };
}
