import type { CrmStore } from "./types";

export function applyKalaoSeed(store: CrmStore): CrmStore {
  return {
    ...store,
    companies: [
      ...store.companies,
      {
        id: "co-101",
        name: "Bâtir Ensemble SARL",
        industry: "BTP",
        website: "https://batir-ensemble.example",
        phone: "+225 27 22 18 40 10",
        email: "chantier@batir-ensemble.example",
        address: "Yopougon Sicogi",
        city: "Abidjan",
        country: "Côte d'Ivoire",
        tags: "BTP",
        ownerName: "Jean-Marc Diallo",
        ownerImage: "avatar-13.jpg",
        image: "company-icon-09.svg",
        status: "active",
      },
      {
        id: "co-102",
        name: "Foncier Lagune",
        industry: "Immobilier",
        website: "https://foncier-lagune.example",
        phone: "+225 07 11 22 33 00",
        email: "biens@foncier-lagune.example",
        address: "Cocody Angré",
        city: "Abidjan",
        country: "Côte d'Ivoire",
        tags: "VIP",
        ownerName: "Fatou N'Diaye",
        ownerImage: "avatar-17.jpg",
        image: "company-icon-10.svg",
        status: "active",
      },
      {
        id: "co-103",
        name: "Plantation N'Zi",
        industry: "Agriculture",
        website: "https://plantation-nzi.example",
        phone: "+225 05 66 77 88 99",
        email: "ferme@plantation-nzi.example",
        address: "Route de Dimbokro",
        city: "Dimbokro",
        country: "Côte d'Ivoire",
        tags: "Collab",
        ownerName: "Ibrahim Traoré",
        ownerImage: "avatar-14.jpg",
        image: "company-icon-11.svg",
        status: "active",
      },
    ],
    contacts: [
      ...store.contacts,
      {
        id: "ct-101",
        companyId: "",
        firstName: "Fatou",
        lastName: "Bamba",
        email: "fatou.bamba@example.com",
        phone: "+225 07 55 10 20 30",
        jobTitle: "Particulier",
        location: "Abidjan",
        tags: "Voyage",
        rating: "4.7",
        image: "avatar-19.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-102",
        companyId: "",
        firstName: "Moussa",
        lastName: "Coulibaly",
        email: "moussa.coulibaly@example.com",
        phone: "+223 76 11 22 33",
        jobTitle: "Particulier",
        location: "Bamako",
        tags: "Immigration",
        rating: "4.4",
        image: "avatar-20.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-103",
        companyId: "",
        firstName: "Aïcha",
        lastName: "Traoré",
        email: "aicha.traore@example.com",
        phone: "+225 05 44 11 22 33",
        jobTitle: "Particulier",
        location: "Bouaké",
        tags: "Événement",
        rating: "4.9",
        image: "avatar-21.jpg",
        flags: "fr.svg",
        status: "active",
      },
      {
        id: "ct-104",
        companyId: "",
        firstName: "Jean",
        lastName: "Koffi",
        email: "jean.koffi@example.com",
        phone: "+225 01 88 77 66 55",
        jobTitle: "Particulier",
        location: "Abidjan",
        tags: "Immobilier",
        rating: "4.1",
        image: "avatar-24.jpg",
        flags: "fr.svg",
        status: "active",
      },
    ],
    catalog: [
      ...store.catalog,
      {
        id: "ca-101",
        kind: "service",
        name: "Forfait voyage Abidjan–Paris (A/R)",
        sku: "VOY-ABJ-CDG",
        description: "Billet + assistance aéroport",
        category: "Voyages",
        unitPrice: 780,
        taxRate: 18,
        status: "active",
        unit: "personne",
        billingType: "one_time",
      },
      {
        id: "ca-102",
        kind: "service",
        name: "Dossier visa Schengen",
        sku: "IMM-VIS-SCH",
        description: "Assistance complète dossier visa",
        category: "Immigration",
        unitPrice: 450,
        taxRate: 18,
        status: "active",
        unit: "dossier",
        billingType: "one_time",
      },
      {
        id: "ca-103",
        kind: "service",
        name: "Couverture photo mariage",
        sku: "EVT-PHO-01",
        description: "Photographe + album numérique",
        category: "Événementiel",
        unitPrice: 350,
        taxRate: 18,
        status: "active",
        unit: "forfait",
        billingType: "one_time",
      },
      {
        id: "ca-104",
        kind: "service",
        name: "Location chapiteau 200 places",
        sku: "EVT-CHAP-200",
        description: "Montage, démontage, transport",
        category: "Événementiel",
        unitPrice: 620,
        taxRate: 18,
        status: "active",
        unit: "jour",
        billingType: "daily",
      },
      {
        id: "ca-105",
        kind: "service",
        name: "Sono + DJ soirée",
        sku: "EVT-SONO-DJ",
        description: "Régie son et animation",
        category: "Événementiel",
        unitPrice: 280,
        taxRate: 18,
        status: "active",
        unit: "soirée",
        billingType: "one_time",
      },
      {
        id: "ca-106",
        kind: "product",
        name: "Engrais NPK 50 kg",
        sku: "AGR-NPK-50",
        description: "Intrant plantation",
        category: "Agriculture",
        unitPrice: 32,
        taxRate: 18,
        status: "active",
        unit: "sac",
        billingType: null,
      },
      {
        id: "ca-107",
        kind: "product",
        name: "Ciment 50 kg",
        sku: "BTP-CIM-50",
        description: "Matériau de construction",
        category: "BTP",
        unitPrice: 9.5,
        taxRate: 18,
        status: "active",
        unit: "sac",
        billingType: null,
      },
      {
        id: "ca-108",
        kind: "service",
        name: "Gestion locative mensuelle",
        sku: "IMO-GEST-M",
        description: "Suivi loyer et charges",
        category: "Immobilier",
        unitPrice: 85,
        taxRate: 18,
        status: "active",
        unit: "mois",
        billingType: "monthly",
      },
    ],
    departments: [
      { id: "dp-01", code: "DEP-VOY", name: "Voyages", headName: "Awa Koné", headImage: "assets/img/profiles/avatar-06.jpg", membersCount: "6 membres", location: "Abidjan", status: "active" },
      { id: "dp-02", code: "DEP-IMM", name: "Immigration", headName: "Fatou N'Diaye", headImage: "assets/img/profiles/avatar-17.jpg", membersCount: "4 membres", location: "Abidjan", status: "active" },
      { id: "dp-03", code: "DEP-COM", name: "Commerce", headName: "Jean-Marc Diallo", headImage: "assets/img/profiles/avatar-13.jpg", membersCount: "8 membres", location: "Abidjan", status: "active" },
      { id: "dp-04", code: "DEP-PRE", name: "Prestations", headName: "Ibrahim Traoré", headImage: "assets/img/profiles/avatar-14.jpg", membersCount: "5 membres", location: "Abidjan", status: "active" },
      { id: "dp-05", code: "DEP-EVE", name: "Événementiel", headName: "Awa Koné", headImage: "assets/img/profiles/avatar-06.jpg", membersCount: "7 membres", location: "Abidjan", status: "active" },
      { id: "dp-06", code: "DEP-AGR", name: "Agriculture", headName: "Ibrahim Traoré", headImage: "assets/img/profiles/avatar-14.jpg", membersCount: "9 membres", location: "Dimbokro", status: "active" },
      { id: "dp-07", code: "DEP-BTP", name: "BTP", headName: "Jean-Marc Diallo", headImage: "assets/img/profiles/avatar-13.jpg", membersCount: "12 membres", location: "Abidjan", status: "active" },
      { id: "dp-08", code: "DEP-IMO", name: "Immobilier", headName: "Fatou N'Diaye", headImage: "assets/img/profiles/avatar-17.jpg", membersCount: "4 membres", location: "Abidjan", status: "active" },
      { id: "dp-09", code: "DEP-RH", name: "RH", headName: "Super Admin Kalao", headImage: "assets/img/profiles/avatar-01.jpg", membersCount: "3 membres", location: "Abidjan", status: "active" },
      { id: "dp-10", code: "DEP-FIN", name: "Finance", headName: "Super Admin Kalao", headImage: "assets/img/profiles/avatar-01.jpg", membersCount: "3 membres", location: "Abidjan", status: "active" },
      { id: "dp-11", code: "DEP-DIR", name: "Direction", headName: "Super Admin Kalao", headImage: "assets/img/profiles/avatar-01.jpg", membersCount: "2 membres", location: "Abidjan", status: "active" },
    ],
    travel: [
      { id: "tr-001", number: "VOY-2026-014", accountName: "Fatou Bamba", accountType: "individual", destination: "Paris (CDG)", departureDate: "03 Oct 2026", returnDate: "18 Oct 2026", status: "Confirmé", amount: 780 },
      { id: "tr-002", number: "VOY-2026-015", accountName: "Société Ivoirienne de Négoce", accountType: "company", destination: "Dubaï", departureDate: "12 Oct 2026", returnDate: "19 Oct 2026", status: "Devis", amount: 2140 },
      { id: "tr-003", number: "VOY-2026-016", accountName: "Moussa Coulibaly", accountType: "individual", destination: "Dakar", departureDate: "22 Sep 2026", returnDate: "28 Sep 2026", status: "En cours", amount: 320 },
    ],
    immigration: [
      { id: "im-001", number: "IMM-2026-008", accountName: "Moussa Coulibaly", accountType: "individual", procedure: "Visa Schengen études", country: "France", status: "Pièces en cours", dueDate: "30 Sep 2026" },
      { id: "im-002", number: "IMM-2026-009", accountName: "Fatou Bamba", accountType: "individual", procedure: "Regroupement familial", country: "Canada", status: "Dépôt prévu", dueDate: "15 Oct 2026" },
      { id: "im-003", number: "IMM-2026-010", accountName: "Atlantic Services CI", accountType: "company", procedure: "Détachement salarié", country: "Maroc", status: "Validé", dueDate: "01 Nov 2026" },
    ],
    events: [
      { id: "ev-001", number: "EVT-2026-021", title: "Mariage Aïcha Traoré", accountName: "Aïcha Traoré", accountType: "individual", eventDate: "25 Oct 2026", services: "Photo, chapiteau, sono", status: "Confirmé", amount: 1250 },
      { id: "ev-002", number: "EVT-2026-022", title: "Lancement Boutique Niani", accountName: "Boutique Niani", accountType: "company", eventDate: "08 Oct 2026", services: "Sono, photo", status: "Préparation", amount: 630 },
      { id: "ev-003", number: "EVT-2026-023", title: "Soirée Hôtel Baobab", accountName: "Hôtel Baobab", accountType: "company", eventDate: "31 Dec 2026", services: "Sono, DJ, éclairage", status: "Devis", amount: 890 },
    ],
    plantations: [
      { id: "pl-001", name: "Bloc cacao N'Zi Nord", crop: "Cacao", location: "Dimbokro", hectares: "42 ha", season: "2026", status: "En production" },
      { id: "pl-002", name: "Palmeraie Comoé", crop: "Palmier à huile", location: "Aboisso", hectares: "18 ha", season: "2026", status: "Entretien" },
      { id: "pl-003", name: "Riziculture Yamoussoukro", crop: "Riz", location: "Yamoussoukro", hectares: "9 ha", season: "2026", status: "Semis" },
    ],
    sites: [
      { id: "st-001", name: "Villa Cocody Angré", accountName: "Jean Koffi", accountType: "individual", location: "Abidjan", progress: "45%", status: "En cours", amount: 68000 },
      { id: "st-002", name: "Entrepôt Port-Bouët", accountName: "Bâtir Ensemble SARL", accountType: "company", location: "Abidjan", progress: "20%", status: "Fondations", amount: 145000 },
      { id: "st-003", name: "Réhabilitation clinique", accountName: "Clinique des Palmiers", accountType: "company", location: "Abidjan", progress: "70%", status: "Finitions", amount: 42000 },
    ],
    properties: [
      { id: "pr-001", name: "Appartement 3 pièces Plateau", kind: "Location", location: "Abidjan", accountName: "Jean Koffi", accountType: "individual", rent: 350, status: "Occupé" },
      { id: "pr-002", name: "Villa F4 Riviera", kind: "Location", location: "Abidjan", accountName: "Foncier Lagune", accountType: "company", rent: 920, status: "Libre" },
      { id: "pr-003", name: "Immeuble bureaux Marcory", kind: "Gestion", location: "Abidjan", accountName: "Foncier Lagune", accountType: "company", rent: 2400, status: "Occupé" },
    ],
    payroll: [
      { id: "py-001", employee: "Awa Koné", department: "Voyages", period: "Sep 2026", salary: 850, bonus: 120, status: "Payé" },
      { id: "py-002", employee: "Jean-Marc Diallo", department: "BTP", period: "Sep 2026", salary: 920, bonus: 80, status: "Payé" },
      { id: "py-003", employee: "Fatou N'Diaye", department: "Immigration", period: "Sep 2026", salary: 780, bonus: 150, status: "À verser" },
      { id: "py-004", employee: "Ibrahim Traoré", department: "Agriculture", period: "Sep 2026", salary: 760, bonus: 60, status: "À verser" },
    ],
  };
}
