

export const all_routes = {
  // dashboard routes
  dashboard:"/dashboard",
  salesDashboard:"/sales-dashboard",
  executiveDashboard:"/executive-dashboard",
  dealsDashboard: "/deals-dashboard",
  leadsDashboard: "/leads-dashboard",
  projectDashboard: "/project-dashboard",
  revenueSummaryDashboard:"/revenue-summary-dashboard",
  growthDashboard:"/growth-dashboard",

  //Super Admin
  superadminDashboard:"/super-admin/dashboard",
  superadminCompany:"/super-admin/company",
  superadminSubscription:"/super-admin/subscription",
  superadminPackagelist:"/super-admin/packages",
  superadminPackageGrid:"/super-admin/packages-grid",
  superadminDomain:"/super-admin/domain",
  superadminPurchaseTransaction:"/super-admin/purchase-transaction",
  tenantSupportTickets:"/super-admin/tenant-support-tickets",
  tenantSupportTicketsGrid:"/super-admin/tenant-support-tickets-grid",
  tenantSupportTicketsDetails:"/super-admin/tenant-ticket-details",
  tenantUsageMetrics:"/super-admin/tenant-usage-metrics",

  //crm routes
  activityCalls: "/crm/activity-calls",
  activityMail: "/crm/activity-mail",
  activityTask: "/crm/activity-task",
  activityMeeting: "/crm/activity-meeting",
  activities: "/crm/activities",
  payments: "/crm/payments",
  tasks: "/crm/tasks",
  tasksImportant: "/crm/tasks-important",
  tasksCompleted: "/crm/tasks-completed",
  campaign: "/crm/campaign",
  campaignComplete: "/crm/campaign-complete",
  campaignArchieve: "/crm/campaign-archieve",
  addCampaign: "/crm/addCampaign",
  analytics: "/crm/analytics",
  contactDetails: "/crm/contact-details",
  dealsGrid: "/crm/deals",
  dealsList: "/crm/deals-list",
  dealsDetails: "/crm/deals-details",
  contactList: "/crm/contact-list",
  leadsKanban: "/leads-kanban",
  pipeline: "/crm/pipeline",
  companyDetails: "/crm/company-details",
  projectDetails: "/crm/project-details",
  contactGrid: "/crm/contact-grid",
  companiesGrid: "/crm/companies-grid",
  companiesList:"/crm/companies-list",
  clients: "/crm/clients",
  travel: "/metiers/voyages",
  immigration: "/metiers/immigration",
  events: "/metiers/evenements",
  plantations: "/metiers/agriculture",
  sites: "/metiers/chantiers",
  siteEquipment: "/metiers/chantiers/materiel",
  siteAssignments: "/metiers/chantiers/equipes",
  siteMilestones: "/metiers/chantiers/avancement",
  properties: "/metiers/immobilier",
  leases: "/metiers/immobilier/baux",
  eventLines: "/metiers/evenements/lignes",
  payroll: "/metiers/paie",
  companiesDetails:"/crm/companies-details",
  account360: "/crm/account-360",
  relationshipMap: "/crm/relationship-map",
  compaignComplete: "/crm/compaign-complete",
  companies: "/companies",
  leadsDetails: "/leads-details",
  leads: "/leads",
  leadsList: "/leads-list",
  projectsGrid: "/crm/projects",
  projectsList: "/crm/project-list",
  ProposalsList: "/crm/proposals-list",
  ProposalsGrid: "/crm/proposals-grid",
  ProposalsView: "/crm/proposals-view",
  ContractsList: "/crm/contracts-list",
  ContractsGrid: "/crm/contracts-grid",
  InvoiceList: "/crm/invoice-list",
  InvoiceGrid: "/crm/invoice-grid",
  invoicesDetails: "/crm/invoices-details",
  estimationList: "/crm/estimation-list",
  estimationKanban: "/crm/estimation-kanban",


  bankAccounts: "/bank-accounts",
  blankPage: "/blank-page",
  calendar: "/calendar",
  dataTables: "/data-tables",
  tablesBasic: "/tables-basic",
  notes: "/notes",
  comingSoon: "/coming-soon",

  // auth routes routes
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  twoStepVerification: "/two-step-verification",
  success: "/success",
  emailVerification: "/email-verification",
  lockScreen: "/lock-screen",
  resetPassword: "/reset-password",

  //ui routes
  alert: "/ui-alert",
  accordion: "/ui-accordion",
  avatar: "/ui-avatar",
  badges: "/ui-badges",
  border: "/ui-border",
  breadcrums: "/ui-breadcrums",
  button: "/ui-buttons",
  buttonGroup: "/ui-button-group",
  cards: "/ui-cards",
  carousel: "/ui-carousel",
  colors: "/ui-colors",
  dropdowns: "/ui-dropdowns",
  images: "/ui-images",
  lightbox: "/ui-lightbox",
  media: "/ui-media",
  modals: "/ui-modals",
  navTabs: "/ui-navtabs",
  offcanvas: "/ui-offcanvas",
  pagination: "/ui-pagination",
  placeholder: "/ui-placeholder",
  popover: "/ui-popover",
  progress: "/ui-progress",
  rangeSlider: "/ui-rangeslider",
  spinner: "/ui-spinner",
  sweetalert: "/ui-alert",
  toasts: "/ui-toasts",
  tooltip: "/ui-tooltip",
  typography: "/ui-typography",
  video: "/ui-video",
  clipboard: "/ui-clipboard",
  counter: "/ui-counter",
  dragandDrop: "/ui-drag-drop",
  rating: "/ui-rating",
  ribbon: "/ui-ribbon",
  stickyNotes: "/ui-sticky-notes",
  textEditor: "/ui-text-editor",
  timeLine: "/ui-timeline",
  scrollBar: "/ui-scrollbar",
  apexChat: "/ui-apexchat",
  featherIcons: "/ui-feather-icon",
  falgIcons: "/ui-flag-icon",
  fantawesome: "/ui-fantawesome",
  materialIcon: "/ui-material-icon",
  pe7icon: "/ui-icon-pe7",
  simpleLineIcon: "/ui-simpleline",
  themifyIcon: "/ui-themify",
  typicon: "/ui-typicon",
  weatherIcon: "/ui-weather-icon",
  basicInput: "/forms-basic-input",
  checkboxandRadios: "/form-checkbox-radios",
  inputGroup: "/form-input-groups",
  gridandGutters: "/form-grid-gutters",
  formSelect: "/form-select",
  formMask: "/form-mask",
  fileUpload: "/form-fileupload",
  horizontalForm: "/form-horizontal",
  verticalForm: "/form-vertical",
  floatingLable: "/form-floating-labels",
  formValidation: "/form-validation",
  reactSelect: "/select",
  formWizard: "/form-wizard",
  iconicIcon: "/icon-ionic",
  chartC3: "/chart-c3",
  chartMorris: "/chart-morris",
  chartFlot: "/chart-flot",
  chartPeity: "/chart-peity",


  //base-ui
  uiAlerts: "/ui-alerts",
  uiAccordion: "/ui-accordion",
  uiAvatar: "/ui-avatar",
  uiBadges: "/ui-badges",
  uiBorders: "/ui-borders",
  uiButtons: "/ui-buttons",
  uiButtonsGroup: "/ui-buttons-group",
  uiBreadcrumb: "/ui-breadcrumb",
  uiCards: "/ui-cards",
  uiCarousel: "/ui-carousel",
  uiCollapse: "/ui-collapse",
  uiColor: "/ui-color",
  uiDropdowns: "/ui-dropdowns",
  uiRatio: "/ui-ratio",
  uiGrid: "/ui-grid",
  uiImage: "/ui-image",
  uiLinks: "/ui-links",
  uiListGroup: "/ui-list-group",
  uiModals: "/ui-modals",
  uiScrollspy: "/ui-scrollspy",
  uiUtilities:"/ui-utilities",
  swiperjs: "/ui-swiperjs",
  sortable: "/ui-sortable",
  tablericons: "/icon-tabler",
  bootstrapicons: "/icon-bootstrap",
  remixicons: "/icon-remix",
  formpicker: "/form-pickers",
  mapleaflet: "/maps-leaflet",
  vectorMap: "/maps-vector",
  notificationbell:"/notifications",

  // pages routes
  error404: "/error-404",
  error500: "/error-500",
  underMaintenance: "/under-maintenance",

  // settings routes
  customFields: "/app-settings/custom-fields",
  invoiceSettings: "/app-settings/invoice-settings",
  printers: "/app-settings/printers",

  bankAccount: "/financial-settings/bank-ccount",
  currencies: "/financial-settings/currencies",
  paymentGateways: "/financial-settings/payment-gateways",
  taxRates: "/financial-settings/tax-rates",

  connectedApps: "/general-settings/connected-apps",
  notification: "/general-settings/notification",
  profile: "/general-settings/profile-settings",
  security: "/general-settings/security",

  banIpAddrress: "/other-settings/ban-ip-address",
  storage: "/other-settings/storage",
  sitemap: "/other-settings/sitemap",
  clearCache: "/other-settings/clear-cache",
  cronjob: "/other-settings/cronjob",
  systemBackup: "/other-settings/system-backup",
  databaseBackup: "/other-settings/database-backup",
  systemUpdate: "/other-settings/system-update",

  emailSettings: "/system-settings/storage",
  gdprCookies: "/system-settings/gdpr-cookies",
  smsGateways: "/system-settings/sms-gateways",

  appearance: "/website-settings/appearance",
  companySettings: "/website-settings/company-settings",
  language: "/website-settings/language",
  localization: "/website-settings/localization",
  preference: "/website-settings/preference",
  prefixes: "/website-settings/prefixes",
  languageWeb: "/website-settings/language-web",
  languageWebEdit: "/website-settings/language-web-edit",
  userPreferences: "/website-settings/user-preferences",

  // reports routes
  companyReports: "/reports/company-reports",
  contactReports: "/reports/contact-reports",
  dealReports: "/reports/deal-reports",
  leadReports: "/reports/lead-reports",
  projectReports: "/reports/project-reports",
  taskReports: "/reports/task-reports",

  // application routes
  todo: "/application/todo",
  todoList: "/application/todo-List",
  email: "/application/email",
  emailReply: "/application/email-reply",
  videoCall: "/application/video-call",
  chat: "/application/chat",
  audioCall: "/application/audio-call",
  callHistory: "/application/call-history",
  fileManager: "/application/file-manager",
  socialfeed: "/application/social-feed",
  kanbanview: "/application/kanban-view",
  invoice: "/application/invoice",
  invoice_details: "/application/invoice-details",
  addInvoices:"/application/add-invoice",
  editInvoices:"/application/edit-invoice",

  // crmsetting routes
  sources: "/crm-setting/sources",
  contactStage: "/crm-setting/contact-stage",
  industry: "/crm-setting/industry",
  calls: "/crm-setting/calls",
  lostReason: "/crm-setting/lost-reason",

  //content routes
  pages: "/content/pages",
  addpages: "/content/add-pages",
  editpages: "/content/edit-pages",
  cities: "/content/cities",
  states: "/content/states",
  testimonials: "/content/testimonials",
  countries: "/content/countries",
  faq: "/content/faq",
  blog: "/content/blogs",
  addblog: "/content/add-blogs",
  editblog: "/content/edit-blogs",
  blogDetails: "/content/blog-details",
  blogComment: "/content/blog-comments",
  blogCategories: "/content/blog-categories",
  blogTags: "/content/blog-tags",

  //userManagement routes
  deleteRequest: "/user-management/delete-request",
  rolesPermissions: "/user-management/roles-permissions",
  manageusers: "/user-management/manage-users",
  permissions: "/user-management/permissions",

  //support routes
  contactMessages: "/support/contact-messages",
  tickets: "/support/tickets",
  ticketsDetails: "/support/tickets-details",

  // membership routes
  membershipplan: "/membership-plans",
  membershipAddon: "/membership-addons",
  membershipTransaction: "/membership-transactions",

  // projects routes (separate from CRM projects)
  projectsGridSeparate: "/projects",
  tasksListSeparate: "/tasks",
  milestones: "/milestones",
  timesheets: "/timesheets",

  // sales crm routes
  products: "/sales-crm/products",
  productDetails: "/sales-crm/product-details",
  opportunitiesList: "/sales-crm/opportunities-list",
  salesTarget: "/sales-crm/sales-target",
  salesTargetTeam: "/sales-crm/sales-target-team",
  quotationsList: "/sales-crm/quotations-list",
  salesOrderList: "/sales-crm/sales-order-list",

  // marketing routes
  emailCampaign: "/marketing/email-campaign",
  emailCampaignCompleted: "/marketing/email-campaign-completed",
  emailCampaignArchieved: "/marketing/email-campaign-archieved",
  smsCampaign: "/marketing/sms-campaign",
  smsCampaignCompleted: "/marketing/sms-campaign-completed",
  smsCampaignArchieved: "/marketing/sms-campaign-archieved",
  socialCampaign: "/marketing/social-campaign",
  socialCampaignCompleted: "/marketing/social-campaign-completed",
  socialCampaignArchieved: "/marketing/social-campaign-archieved",
  whatsappCampaign: "/marketing/whatsapp-campaign",
  whatsappCampaignCompleted: "/marketing/whatsapp-campaign-completed",
  whatsappCampaignArchieved: "/marketing/whatsapp-campaign-archieved",
  emailMarketing: "/marketing/email-marketing",
  emailEngagement: "/marketing/email-engagement",

  // hrm routes
  attendance: "/hrm/attendance",
  leaveRequests: "/hrm/leave-requests",
  holidays: "/hrm/holidays",

  // additional user management routes
  departments: "/user-management/departments",
  departmentsList: "/user-management/departments-list",
  teamsList: "/user-management/teams-list",
  invitationsList: "/user-management/invitations-list",
  staffDirectoryGrid: "/user-management/staff-directory-grid",
  staffDirectoryList: "/user-management/staff-directory-list",
  userActivityLogs: "/user-management/user-activity-logs",
  loginHistory: "/user-management/login-history",
  deviceManagement: "/user-management/device-management",

  // additional crm settings routes
  salesTargetsSettings: "/crm-setting/sales-targets-settings",
  salesTargetsBreakdownSettings: "/crm-setting/sales-targets-breakdown-settings",
  salesTargetsTeamsSettings: "/crm-setting/sales-targets-teams-settings",
  discountRulesSettings: "/crm-setting/discount-rules-settings",
  appliedDiscountLog: "/crm-setting/applied-discount-log",

  // additional report routes
  leadFunnelReport: "/reports/lead-funnel-report",
  leadAgingReport: "/reports/lead-aging-report",
  leadConversionTimeReport: "/reports/lead-conversion-time-report",
  dealConversionReport: "/reports/deal-conversion-report",
  dealAgingReport: "/reports/deal-aging-report",
  lostDealAnalysisReport: "/reports/lost-deal-analysis-report",
  pipelineStageReport: "/reports/pipeline-stage-report",
  revenueReport: "/reports/revenue-report",
  userActivityReport: "/reports/user-activity-report",
  userLoginReport: "/reports/user-login-report",
  teamPerformanceReport: "/reports/team-performance-report",
  salesRepComparisonReport: "/reports/sales-rep-comparison-report",
  proposalReport: "/reports/proposal-report",
  proposalConversionRateReport: "/reports/proposal-conversion-rate-report",
  contractReport: "/reports/contract-report",
  contractRenewalExpiryReport: "/reports/contract-renewal-expiry-report",
  estimationReport: "/reports/estimation-report",
  attendanceSummaryReport: "/reports/attendance-summary-report",
  leaveBalanceSummaryReport: "/reports/leave-balance-summary-report",

  // ai-crm routes
  aiCommandCenter: "/ai-crm/ai-command-center",
  aiInsights: "/ai-crm/ai-insights",
  aiLeadScoring: "/ai-crm/ai-lead-scoring",
  aiEmailComposer: "/ai-crm/ai-email-composer",
  aiSettings: "/ai-crm/ai-settings",
  askYourData: "/ai-crm/ask-your-data",
  callSummary: "/ai-crm/call-summary",
  dealRiskAnalysis: "/ai-crm/deal-risk-analysis",

  // automation routes
  workflowBuilder: "/automation/workflow-builder",
  automationRules: "/automation/automation-rules",
  webhooks: "/automation/webhooks",
  automationLogs: "/automation/automation-logs",

  // additional reports routes (new report pages)
  reportBuilder: "/reports/report-builder",
  salesForecasting: "/reports/sales-forecasting",
  salesVelocity: "/reports/sales-velocity",
  scheduledReports: "/reports/scheduled-reports",
  winLossAnalysis: "/reports/win-loss-analysis",

  // additional crm-setting routes
  importWizard: "/crm-setting/import-wizard",

  //Layouts Pages
  layoutMini: "/layout-mini",
  hoverView: "/layout-hoverview",
  hidden: "/layout-hidden",
  fullWidth: "/layout-fullwidth",
  HorizontalSingle: "/layout-horizontal-single",
  WithoutHeader: "/layout-without-header",
  layoutRtl: "/layout-rtl",
  Detached: "/layout-detached",
  Dark: "/layout-dark",

  // Next.js-only constants (no React counterpart)
  chart: "/ui-chartjs",
  chartJs: "/chart-js",
  formEditor: "/form-editors",
  dataTable: "/tables-basic",
  tableBasic: "/data-tables",
};
