export interface AttendanceData {
  key: string;
  AttendanceId: string;
  EmployeeId: string;
  EmployeeName: string;
  EmployeeImage: string;
  Date: string;
  Status: "Present" | "Absent";
  LocationName: string;
  LocationImage: string;
  Remarks: "-" | "info";
}

export const AttendanceListData: AttendanceData[] = [
  {
    key: "1",
    AttendanceId: "#ATT301",
    EmployeeId: "#EMP301",
    EmployeeName: "Elijah Blackwood",
    EmployeeImage: "assets/img/profiles/avatar-15.jpg",
    Date: "25 Sep 2025",
    Status: "Present",
    LocationName: "USA",
    LocationImage: "assets/img/flags/us.svg",
    Remarks: "-",
  },
  {
    key: "2",
    AttendanceId: "#ATT302",
    EmployeeId: "#EMP302",
    EmployeeName: "Scarlett Beaumont",
    EmployeeImage: "assets/img/profiles/avatar-05.jpg",
    Date: "29 Sep 2025",
    Status: "Absent",
    LocationName: "UAE",
    LocationImage: "assets/img/flags/ae.svg",
    Remarks: "info",
  },
  {
    key: "3",
    AttendanceId: "#ATT303",
    EmployeeId: "#EMP303",
    EmployeeName: "Owen Sterling",
    EmployeeImage: "assets/img/profiles/avatar-01.jpg",
    Date: "05 Oct 2025",
    Status: "Absent",
    LocationName: "Germany",
    LocationImage: "assets/img/flags/de.svg",
    Remarks: "-",
  },
  {
    key: "4",
    AttendanceId: "#ATT304",
    EmployeeId: "#EMP304",
    EmployeeName: "Hazel Davenport",
    EmployeeImage: "assets/img/profiles/avatar-15.jpg",
    Date: "14 Oct 2025",
    Status: "Absent",
    LocationName: "France",
    LocationImage: "assets/img/flags/fr.svg",
    Remarks: "info",
  },
  {
    key: "5",
    AttendanceId: "#ATT305",
    EmployeeId: "#EMP305",
    EmployeeName: "Violet Ainsworth",
    EmployeeImage: "assets/img/profiles/avatar-11.jpg",
    Date: "15 Nov 2025",
    Status: "Present",
    LocationName: "India",
    LocationImage: "assets/img/flags/india.svg",
    Remarks: "-",
  },
  {
    key: "6",
    AttendanceId: "#ATT306",
    EmployeeId: "#EMP306",
    EmployeeName: "Milo Rutherford",
    EmployeeImage: "assets/img/profiles/avatar-09.jpg",
    Date: "25 Nov 2025",
    Status: "Absent",
    LocationName: "Brazil",
    LocationImage: "assets/img/flags/brazil.svg",
    Remarks: "info",
  },
  {
    key: "7",
    AttendanceId: "#ATT307",
    EmployeeId: "#EMP307",
    EmployeeName: "Luna Ashworth",
    EmployeeImage: "assets/img/profiles/avatar-07.jpg",
    Date: "08 Dec 2025",
    Status: "Present",
    LocationName: "Mexico",
    LocationImage: "assets/img/flags/mexico.svg",
    Remarks: "-",
  },
  {
    key: "8",
    AttendanceId: "#ATT308",
    EmployeeId: "#EMP308",
    EmployeeName: "Scarlett Beaumont",
    EmployeeImage: "assets/img/profiles/avatar-15.jpg",
    Date: "21 Dec 2025",
    Status: "Absent",
    LocationName: "China",
    LocationImage: "assets/img/flags/china.svg",
    Remarks: "-",
  },
  {
    key: "9",
    AttendanceId: "#ATT309",
    EmployeeId: "#EMP309",
    EmployeeName: "Jasper Huntington",
    EmployeeImage: "assets/img/profiles/avatar-12.jpg",
    Date: "01 Jan 2024",
    Status: "Present",
    LocationName: "Russia",
    LocationImage: "assets/img/flags/russia.svg",
    Remarks: "-",
  },
  {
    key: "10",
    AttendanceId: "#ATT310",
    EmployeeId: "#EMP310",
    EmployeeName: "Caleb Worthington",
    EmployeeImage: "assets/img/profiles/avatar-14.jpg",
    Date: "12 Jan 2024",
    Status: "Present",
    LocationName: "France",
    LocationImage: "assets/img/flags/fr.svg",
    Remarks: "-",
  },
  {
    key: "11",
    AttendanceId: "#ATT311",
    EmployeeId: "#EMP311",
    EmployeeName: "Elijah Blackwood",
    EmployeeImage: "assets/img/profiles/avatar-15.jpg",
    Date: "16 Jan 2024",
    Status: "Present",
    LocationName: "Italy",
    LocationImage: "assets/img/flags/italy.svg",
    Remarks: "-",
  },
  {
    key: "12",
    AttendanceId: "#ATT312",
    EmployeeId: "#EMP312",
    EmployeeName: "Aurora Lancaster",
    EmployeeImage: "assets/img/profiles/avatar-11.jpg",
    Date: "12 Jan 2024",
    Status: "Present",
    LocationName: "Canada",
    LocationImage: "assets/img/flags/canada.svg",
    Remarks: "-",
  },
];
