export interface OpportunityListItem {
  key: string;
  OpportunityID: string;
  OpportunityName: string;
  Account: string;
  AccountImage: string;
  ExpectedValue: string;
  Stage: string;
  ExpectedCloseDate: string;
  Status: string;
}

export const OpportunitiesListData: OpportunityListItem[] = [
  {
    key: "1",
    OpportunityID: "#OPP114",
    OpportunityName: "Enterprise Software",
    Account: "NovaWave LLC",
    AccountImage: "company-icon-01.svg",
    ExpectedValue: "FCFA 250,000",
    Stage: "Proposal Sent",
    ExpectedCloseDate: "15 Dec 2026",
    Status: "Open",
  },
  {
    key: "2",
    OpportunityID: "#OPP115",
    OpportunityName: "Cloud Migration Project",
    Account: "BlueSky Industries",
    AccountImage: "company-icon-02.svg",
    ExpectedValue: "FCFA 50,000",
    Stage: "Negotiation",
    ExpectedCloseDate: "12 Nov 2026",
    Status: "Closed",
  },
  {
    key: "3",
    OpportunityID: "#OPP116",
    OpportunityName: "Annual Support Renewal",
    Account: "SilverHawk",
    AccountImage: "company-icon-03.svg",
    ExpectedValue: "FCFA 45,000",
    Stage: "Lost",
    ExpectedCloseDate: "06 Oct 2026",
    Status: "Open",
  },
  {
    key: "4",
    OpportunityID: "#OPP117",
    OpportunityName: "Digital Transformation",
    Account: "SummitPeak",
    AccountImage: "company-icon-04.svg",
    ExpectedValue: "FCFA 780,000",
    Stage: "Closed Won",
    ExpectedCloseDate: "14 Sep 2026",
    Status: "Open",
  },
  {
    key: "5",
    OpportunityID: "#OPP118",
    OpportunityName: "CRM Implementation",
    Account: "RiverStone Ventur",
    AccountImage: "company-icon-05.svg",
    ExpectedValue: "FCFA 80,000",
    Stage: "Closed Won",
    ExpectedCloseDate: "23 Aug 2026",
    Status: "Open",
  },
  {
    key: "6",
    OpportunityID: "#OPP119",
    OpportunityName: "Data Analytics Platform",
    Account: "CoastalStar Co.",
    AccountImage: "company-icon-06.svg",
    ExpectedValue: "FCFA 40,000",
    Stage: "Negotiation",
    ExpectedCloseDate: "16 Jul 2026",
    Status: "Open",
  },
  {
    key: "7",
    OpportunityID: "#OPP120",
    OpportunityName: "Mobile App Development",
    Account: "HarborView",
    AccountImage: "company-icon-07.svg",
    ExpectedValue: "FCFA 7,000",
    Stage: "Lost",
    ExpectedCloseDate: "09 Jun 2026",
    Status: "Open",
  },
  {
    key: "8",
    OpportunityID: "#OPP121",
    OpportunityName: "Infrastructure Upgrade",
    Account: "Golden Gate Ltd",
    AccountImage: "company-icon-08.svg",
    ExpectedValue: "FCFA 01,23,000",
    Stage: "Lost",
    ExpectedCloseDate: "15 May 2026",
    Status: "Open",
  },
  {
    key: "9",
    OpportunityID: "#OPP122",
    OpportunityName: "POS",
    Account: "Consulting Services",
    AccountImage: "company-icon-06.svg",
    ExpectedValue: "FCFA 780,000",
    Stage: "Negotiation",
    ExpectedCloseDate: "19 Apr 2026",
    Status: "Open",
  },
  {
    key: "10",
    OpportunityID: "#OPP123",
    OpportunityName: "Digital Transformation",
    Account: "Redwood Inc",
    AccountImage: "company-icon-09.svg",
    ExpectedValue: "FCFA 04,10,000",
    Stage: "Negotiation",
    ExpectedCloseDate: "28 Mar 2026",
    Status: "Open",
  },
  {
    key: "11",
    OpportunityID: "#OPP124",
    OpportunityName: "CRM Implementation",
    Account: "Redwood Inc",
    AccountImage: "company-icon-09.svg",
    ExpectedValue: "FCFA 02,19,000",
    Stage: "Negotiation",
    ExpectedCloseDate: "25 Jan 2026",
    Status: "Open",
  },
  {
    key: "12",
    OpportunityID: "#OPP125",
    OpportunityName: "Data Analytics Platform",
    Account: "Ventur",
    AccountImage: "company-icon-08.svg",
    ExpectedValue: "FCFA 60,000",
    Stage: "Negotiation",
    ExpectedCloseDate: "29 Jan 2026",
    Status: "Open",
  },
];
