export interface SalesTargetsSettingsListDataType {
  key: string;
  TargetID: string;
  TargetName: string;
  Image: string;
  Period: string;
  StartDate: string;
  EndDate: string;
  TargetRevenue: string;
  Status: string;
}

export const SalesTargetsSettingsListData: SalesTargetsSettingsListDataType[] = [
  {
    key: "1",
    TargetID: "#SAT0020",
    TargetName: "Elijah Blackwood",
    Image: "assets/img/profiles/avatar-15.jpg",
    Period: "Dec 2026",
    StartDate: "25 Sep 2025",
    EndDate: "31 Jul 2026",
    TargetRevenue: "$250,000",
    Status: "Completed",
  },
  {
    key: "2",
    TargetID: "#SAT0019",
    TargetName: "Scarlett Beaumont",
    Image: "assets/img/profiles/avatar-05.jpg",
    Period: "Nov 2026",
    StartDate: "29 Sep 2025",
    EndDate: "30 Apr 2025",
    TargetRevenue: "$50,000",
    Status: "Failed",
  },
  {
    key: "3",
    TargetID: "#SAT0018",
    TargetName: "Owen Sterling",
    Image: "assets/img/profiles/avatar-01.jpg",
    Period: "Oct 2026",
    StartDate: "05 Oct 2025",
    EndDate: "30 Jun 2026",
    TargetRevenue: "$45,000",
    Status: "Inprogress",
  },
  {
    key: "4",
    TargetID: "#SAT0017",
    TargetName: "Hazel Davenport",
    Image: "assets/img/profiles/avatar-15.jpg",
    Period: "Sep 2026",
    StartDate: "14 Oct 2025",
    EndDate: "31 May 2026",
    TargetRevenue: "$780,000",
    Status: "Inprogress",
  },
  {
    key: "5",
    TargetID: "#SAT0016",
    TargetName: "Violet Ainsworth",
    Image: "assets/img/profiles/avatar-11.jpg",
    Period: "Aug 2026",
    StartDate: "15 Nov 2025",
    EndDate: "30 Apr 2026",
    TargetRevenue: "$80,000",
    Status: "Completed",
  },
  {
    key: "6",
    TargetID: "#SAT0015",
    TargetName: "Milo Rutherford",
    Image: "assets/img/profiles/avatar-09.jpg",
    Period: "Jul 2026",
    StartDate: "25 Nov 2025",
    EndDate: "31 Mar 2026",
    TargetRevenue: "$40,000",
    Status: "Failed",
  },
  {
    key: "7",
    TargetID: "#SAT0014",
    TargetName: "Luna Ashworth",
    Image: "assets/img/profiles/avatar-07.jpg",
    Period: "Jun 2026",
    StartDate: "08 Dec 2025",
    EndDate: "31 Mar 2026",
    TargetRevenue: "$7,000",
    Status: "Completed",
  },
  {
    key: "8",
    TargetID: "#SAT0013",
    TargetName: "Scarlett Beaumont",
    Image: "assets/img/profiles/avatar-15.jpg",
    Period: "Apr 2026",
    StartDate: "21 Dec 2025",
    EndDate: "28 Feb 2026",
    TargetRevenue: "$01,23,000",
    Status: "Failed",
  },
  {
    key: "9",
    TargetID: "#SAT0012",
    TargetName: "Jasper Huntington",
    Image: "assets/img/profiles/avatar-12.jpg",
    Period: "Apr 2026",
    StartDate: "01 Jan 2024",
    EndDate: "31 Mar 2026",
    TargetRevenue: "$780,000",
    Status: "Completed",
  },
  {
    key: "10",
    TargetID: "#SAT0011",
    TargetName: "Caleb Worthington",
    Image: "assets/img/profiles/avatar-14.jpg",
    Period: "Jan 2026",
    StartDate: "12 Jan 2024",
    EndDate: "31 Jan 2026",
    TargetRevenue: "$04,10,000",
    Status: "Completed",
  },
  {
    key: "11",
    TargetID: "#SAT0010",
    TargetName: "Elijah Blackwood",
    Image: "assets/img/profiles/avatar-15.jpg",
    Period: "Apr 2026",
    StartDate: "16 Jan 2024",
    EndDate: "31 Jan 2026",
    TargetRevenue: "$02,19,000",
    Status: "Completed",
  },
  {
    key: "12",
    TargetID: "#SAT0009",
    TargetName: "Aurora Lancaster",
    Image: "assets/img/profiles/avatar-11.jpg",
    Period: "Oct 2026",
    StartDate: "12 Jan 2024",
    EndDate: "31 Jan 2026",
    TargetRevenue: "$60,000",
    Status: "Completed",
  },
];
