export interface SalesTargetListItem {
  key: string;
  targetId: string;
  user: string;
  userImage: string;
  period: string;
  targetAmount: string;
  achievedSales: string;
  achievedTrend: "Positive" | "Negative";
  achievementPercent: string;
  status: "Achieved" | "Inprogress" | "At Risk";
}

export const SalesTargetListData: SalesTargetListItem[] = [
  {
    key: "1",
    targetId: "#SLT0020",
    user: "Elijah Blackwood",
    userImage: "assets/img/profiles/avatar-15.jpg",
    period: "Dec 2026",
    targetAmount: "$250,000",
    achievedSales: "$250,000",
    achievedTrend: "Positive",
    achievementPercent: "60%",
    status: "Achieved",
  },
  {
    key: "2",
    targetId: "#SLT0019",
    user: "Scarlett Beaumont",
    userImage: "assets/img/profiles/avatar-05.jpg",
    period: "Nov 2026",
    targetAmount: "$50,000",
    achievedSales: "80",
    achievedTrend: "Negative",
    achievementPercent: "0%",
    status: "At Risk",
  },
  {
    key: "3",
    targetId: "#SLT0018",
    user: "Owen Sterling",
    userImage: "assets/img/profiles/avatar-01.jpg",
    period: "Oct 2026",
    targetAmount: "$45,000",
    achievedSales: "$40,000",
    achievedTrend: "Negative",
    achievementPercent: "50%",
    status: "Inprogress",
  },
  {
    key: "4",
    targetId: "#SLT0017",
    user: "Hazel Davenport",
    userImage: "assets/img/profiles/avatar-15.jpg",
    period: "Sep 2026",
    targetAmount: "$780,000",
    achievedSales: "$45,000",
    achievedTrend: "Negative",
    achievementPercent: "80%",
    status: "Inprogress",
  },
  {
    key: "5",
    targetId: "#SLT0016",
    user: "Violet Ainsworth",
    userImage: "assets/img/profiles/avatar-11.jpg",
    period: "Aug 2026",
    targetAmount: "$80,000",
    achievedSales: "$85,000",
    achievedTrend: "Positive",
    achievementPercent: "100%",
    status: "Achieved",
  },
  {
    key: "6",
    targetId: "#SLT0015",
    user: "Milo Rutherford",
    userImage: "assets/img/profiles/avatar-09.jpg",
    period: "Jul 2026",
    targetAmount: "$40,000",
    achievedSales: "$180,000",
    achievedTrend: "Negative",
    achievementPercent: "60%",
    status: "At Risk",
  },
  {
    key: "7",
    targetId: "#SLT0014",
    user: "Luna Ashworth",
    userImage: "assets/img/profiles/avatar-07.jpg",
    period: "Jun 2026",
    targetAmount: "$7,000",
    achievedSales: "$90,000",
    achievedTrend: "Positive",
    achievementPercent: "100%",
    status: "Achieved",
  },
  {
    key: "8",
    targetId: "#SLT0013",
    user: "Scarlett Beaumont",
    userImage: "assets/img/profiles/avatar-15.jpg",
    period: "Apr 2026",
    targetAmount: "$01,23,000",
    achievedSales: "$80,000",
    achievedTrend: "Negative",
    achievementPercent: "10%",
    status: "At Risk",
  },
  {
    key: "9",
    targetId: "#SLT0012",
    user: "Jasper Huntington",
    userImage: "assets/img/profiles/avatar-12.jpg",
    period: "Apr 2026",
    targetAmount: "$780,000",
    achievedSales: "$1180,000",
    achievedTrend: "Positive",
    achievementPercent: "100%",
    status: "Achieved",
  },
  {
    key: "10",
    targetId: "#SLT0011",
    user: "Caleb Worthington",
    userImage: "assets/img/profiles/avatar-14.jpg",
    period: "Jan 2026",
    targetAmount: "$04,10,000",
    achievedSales: "$14,10,000",
    achievedTrend: "Positive",
    achievementPercent: "50%",
    status: "Achieved",
  },
  {
    key: "11",
    targetId: "#SLT0010",
    user: "Elijah Blackwood",
    userImage: "assets/img/profiles/avatar-15.jpg",
    period: "Apr 2026",
    targetAmount: "$02,19,000",
    achievedSales: "04,10,000",
    achievedTrend: "Positive",
    achievementPercent: "60%",
    status: "Achieved",
  },
  {
    key: "12",
    targetId: "#SLT0009",
    user: "Aurora Lancaster",
    userImage: "assets/img/profiles/avatar-11.jpg",
    period: "Oct 2026",
    targetAmount: "$60,000",
    achievedSales: "4,10,000",
    achievedTrend: "Positive",
    achievementPercent: "60%",
    status: "Achieved",
  },
];

export const SalesTargetFilterUsers = [
  { key: "1", name: "Elizabeth Morgan", image: "assets/img/users/user-06.jpg" },
  { key: "2", name: "Katherine Brooks", image: "assets/img/users/user-40.jpg" },
  { key: "3", name: "Sophia Lopez", image: "assets/img/users/user-05.jpg" },
  { key: "4", name: "John Michael", image: "assets/img/users/user-10.jpg" },
  { key: "5", name: "Natalie Brooks", image: "assets/img/users/user-15.jpg" },
];
