export interface SalesOrderListItem {
  key: string;
  OrderID: string;
  Client: string;
  ClientImage: string;
  OrderDate: string;
  OrderValue: string;
  NetAmount: string;
  PaymentStatus: string;
  OrderStatus: string;
}

export const SalesOrderListData: SalesOrderListItem[] = [
  {
    key: "1",
    OrderID: "#SOR0020",
    Client: "NovaWave LLC",
    ClientImage: "company-icon-01.svg",
    OrderDate: "15 Dec 2026",
    OrderValue: "FCFA 200000",
    NetAmount: "FCFA 250,000",
    PaymentStatus: "Paid",
    OrderStatus: "Confirmed",
  },
  {
    key: "2",
    OrderID: "#SOR0019",
    Client: "BlueSky Industries",
    ClientImage: "company-icon-02.svg",
    OrderDate: "12 Nov 2026",
    OrderValue: "FCFA 300000",
    NetAmount: "FCFA 50,000",
    PaymentStatus: "Pending",
    OrderStatus: "Cancelled",
  },
  {
    key: "3",
    OrderID: "#SOR0018",
    Client: "SilverHawk",
    ClientImage: "company-icon-03.svg",
    OrderDate: "06 Oct 2026",
    OrderValue: "FCFA 200000",
    NetAmount: "FCFA 45,000",
    PaymentStatus: "Overdue",
    OrderStatus: "Confirmed",
  },
  {
    key: "4",
    OrderID: "#SOR0017",
    Client: "SummitPeak",
    ClientImage: "company-icon-04.svg",
    OrderDate: "14 Sep 2026",
    OrderValue: "FCFA 300000",
    NetAmount: "FCFA 780,000",
    PaymentStatus: "Paid",
    OrderStatus: "Confirmed",
  },
  {
    key: "5",
    OrderID: "#SOR0016",
    Client: "RiverStone Ventur",
    ClientImage: "company-icon-05.svg",
    OrderDate: "23 Aug 2026",
    OrderValue: "FCFA 120000",
    NetAmount: "FCFA 80,000",
    PaymentStatus: "Paid",
    OrderStatus: "Inprogress",
  },
  {
    key: "6",
    OrderID: "#SOR0015",
    Client: "CoastalStar Co.",
    ClientImage: "company-icon-06.svg",
    OrderDate: "16 Jul 2026",
    OrderValue: "FCFA 200000",
    NetAmount: "FCFA 40,000",
    PaymentStatus: "Pending",
    OrderStatus: "Confirmed",
  },
  {
    key: "7",
    OrderID: "#SOR0014",
    Client: "HarborView",
    ClientImage: "company-icon-07.svg",
    OrderDate: "09 Jun 2026",
    OrderValue: "FCFA 200000",
    NetAmount: "FCFA 7,000",
    PaymentStatus: "Overdue",
    OrderStatus: "Confirmed",
  },
  {
    key: "8",
    OrderID: "#SOR0013",
    Client: "Golden Gate Ltd",
    ClientImage: "company-icon-08.svg",
    OrderDate: "15 May 2026",
    OrderValue: "FCFA 45,000",
    NetAmount: "FCFA 01,23,000",
    PaymentStatus: "Overdue",
    OrderStatus: "Inprogress",
  },
  {
    key: "9",
    OrderID: "#SOR0012",
    Client: "Consulting Services",
    ClientImage: "company-icon-06.svg",
    OrderDate: "19 Apr 2026",
    OrderValue: "FCFA 200000",
    NetAmount: "FCFA 780,000",
    PaymentStatus: "Pending",
    OrderStatus: "Cancelled",
  },
  {
    key: "10",
    OrderID: "#SOR0011",
    Client: "Redwood Inc",
    ClientImage: "company-icon-09.svg",
    OrderDate: "28 Mar 2026",
    OrderValue: "FCFA 80,000",
    NetAmount: "FCFA 04,10,000",
    PaymentStatus: "Pending",
    OrderStatus: "Cancelled",
  },
  {
    key: "11",
    OrderID: "#SOR0010",
    Client: "Redwood Inc",
    ClientImage: "company-icon-09.svg",
    OrderDate: "25 Jan 2026",
    OrderValue: "FCFA 780,000",
    NetAmount: "FCFA 02,19,000",
    PaymentStatus: "Pending",
    OrderStatus: "Confirmed",
  },
  {
    key: "12",
    OrderID: "#SOR0009",
    Client: "Ventur",
    ClientImage: "company-icon-08.svg",
    OrderDate: "29 Jan 2026",
    OrderValue: "FCFA 300000",
    NetAmount: "FCFA 60,000",
    PaymentStatus: "Pending",
    OrderStatus: "Inprogress",
  },
];
