export interface SalesTargetTeamListItem {
  key: string;
  targetId: string;
  team: string;
  period: string;
  targetAmount: string;
  achievedSales: string;
  achievedTrend: "Positive" | "Negative";
  achievementPercent: string;
  status: "Achieved" | "Inprogress" | "At Risk";
}

export const SalesTargetTeamListData: SalesTargetTeamListItem[] = [
  {
    key: "1",
    targetId: "#SLT0020",
    team: "Development",
    period: "Dec 2026",
    targetAmount: "FCFA 250,000",
    achievedSales: "FCFA 250,000",
    achievedTrend: "Positive",
    achievementPercent: "60%",
    status: "Achieved",
  },
  {
    key: "2",
    targetId: "#SLT0019",
    team: "Marketing",
    period: "Nov 2026",
    targetAmount: "FCFA 50,000",
    achievedSales: "80",
    achievedTrend: "Negative",
    achievementPercent: "0%",
    status: "At Risk",
  },
  {
    key: "3",
    targetId: "#SLT0018",
    team: "Support",
    period: "Oct 2026",
    targetAmount: "FCFA 45,000",
    achievedSales: "FCFA 40,000",
    achievedTrend: "Negative",
    achievementPercent: "50%",
    status: "Inprogress",
  },
  {
    key: "4",
    targetId: "#SLT0017",
    team: "Sales",
    period: "Sep 2026",
    targetAmount: "FCFA 780,000",
    achievedSales: "FCFA 45,000",
    achievedTrend: "Negative",
    achievementPercent: "80%",
    status: "Inprogress",
  },
  {
    key: "5",
    targetId: "#SLT0016",
    team: "Sales",
    period: "Aug 2026",
    targetAmount: "FCFA 80,000",
    achievedSales: "FCFA 85,000",
    achievedTrend: "Positive",
    achievementPercent: "100%",
    status: "Achieved",
  },
  {
    key: "6",
    targetId: "#SLT0015",
    team: "IT Support",
    period: "Jul 2026",
    targetAmount: "FCFA 40,000",
    achievedSales: "FCFA 180,000",
    achievedTrend: "Negative",
    achievementPercent: "60%",
    status: "At Risk",
  },
  {
    key: "7",
    targetId: "#SLT0014",
    team: "HR",
    period: "Jun 2026",
    targetAmount: "FCFA 7,000",
    achievedSales: "FCFA 90,000",
    achievedTrend: "Positive",
    achievementPercent: "100%",
    status: "Achieved",
  },
  {
    key: "8",
    targetId: "#SLT0013",
    team: "Research",
    period: "Apr 2026",
    targetAmount: "FCFA 01,23,000",
    achievedSales: "FCFA 80,000",
    achievedTrend: "Negative",
    achievementPercent: "10%",
    status: "At Risk",
  },
  {
    key: "9",
    targetId: "#SLT0012",
    team: "Operations",
    period: "Apr 2026",
    targetAmount: "FCFA 780,000",
    achievedSales: "FCFA 1180,000",
    achievedTrend: "Positive",
    achievementPercent: "100%",
    status: "Achieved",
  },
  {
    key: "10",
    targetId: "#SLT0011",
    team: "Sales",
    period: "Jan 2026",
    targetAmount: "FCFA 04,10,000",
    achievedSales: "FCFA 14,10,000",
    achievedTrend: "Positive",
    achievementPercent: "50%",
    status: "Achieved",
  },
  {
    key: "11",
    targetId: "#SLT0010",
    team: "Analytics",
    period: "Apr 2026",
    targetAmount: "FCFA 02,19,000",
    achievedSales: "04,10,000",
    achievedTrend: "Positive",
    achievementPercent: "60%",
    status: "Achieved",
  },
  {
    key: "12",
    targetId: "#SLT0009",
    team: "Design",
    period: "Oct 2026",
    targetAmount: "FCFA 60,000",
    achievedSales: "4,10,000",
    achievedTrend: "Positive",
    achievementPercent: "60%",
    status: "Achieved",
  },
];

export const SalesTargetTeamFilterTeams = [
  { key: "1", name: "Development" },
  { key: "2", name: "Marketing" },
  { key: "3", name: "Sales" },
  { key: "4", name: "Support" },
  { key: "5", name: "Analytics" },
];
