export const usageMetricesData = [
  {
    Ticket_ID: "#TKT0011",
    Tenant_Name: "Blue Chip Inc",
    Plan: "Mobile App Crash",
    Status: "Inactive",
    Active_Users: 35,
    Storage_Used: 14,
    Storage_Limit: 20,
    API_Calls: "72,876",
    Action: "View Details Delete",
  },
  {
    Ticket_ID: "#TKT0012",
    Tenant_Name: "Titanium Media",
    Plan: "Subscription Renewal",
    Status: "Inactive",
    Active_Users: 80,
    Storage_Used: 60,
    Storage_Limit: 100,
    API_Calls: "92,653",
    Action: "View Details Delete",
  },
  {
    Ticket_ID: "#TKT0013",
    Tenant_Name: "Velocity Labs",
    Plan: "Data Export Issue",
    Status: "Inactive",
    Active_Users: 35,
    Storage_Used: 30,
    Storage_Limit: 100,
    API_Calls: "38,148",
    Action: "View Details Delete",
  },
  {
    Ticket_ID: "#TKT0014",
    Tenant_Name: "Zenith Corp",
    Plan: "Password Reset Help",
    Status: "Inactive",
    Active_Users: 52,
    Storage_Used: 58,
    Storage_Limit: 100,
    API_Calls: "24,578",
    Action: "View Details Delete",
  },
  {
    Ticket_ID: "#TKT0015",
    Tenant_Name: "Eco-Stream",
    Plan: "Dashboard Not Loading",
    Status: "Inactive",
    Active_Users: 35,
    Storage_Used: 26,
    Storage_Limit: 50,
    API_Calls: "32,350",
    Action: "View Details Delete",
  },
  {
    Ticket_ID: "#TKT0016",
    Tenant_Name: "Quantum Leap",
    Plan: "API Integration Fail",
    Status: "Inactive",
    Active_Users: 45,
    Storage_Used: 17,
    Storage_Limit: 20,
    API_Calls: "26,112",
    Action: "View Details Delete",
  },
  {
    Ticket_ID: "#TKT0017",
    Tenant_Name: "Alpha Solutions",
    Plan: "UI Bug Report",
    Status: "Inactive",
    Active_Users: 70,
    Storage_Used: 42,
    Storage_Limit: 50,
    API_Calls: "80,145",
    Action: "View Details Delete",
  },
  {
    Ticket_ID: "#TKT0018",
    Tenant_Name: "Nebula Cloud",
    Plan: "Payment Timeout",
    Status: "Inactive",
    Active_Users: 60,
    Storage_Used: 32,
    Storage_Limit: 50,
    API_Calls: "35,800",
    Action: "View Details Delete",
  },
  {
    Ticket_ID: "#TKT0019",
    Tenant_Name: "Veridian Systems",
    Plan: "Invoice Mismatch",
    Status: "Inactive",
    Active_Users: 40,
    Storage_Used: 65,
    Storage_Limit: 100,
    API_Calls: "42,270",
    Action: "View Details Delete",
  },
  {
    Ticket_ID: "#TKT0020",
    Tenant_Name: "Sunburst Tech",
    Plan: "Advanced",
    Status: "Active",
    Active_Users: 50,
    Storage_Used: 16,
    Storage_Limit: 20,
    API_Calls: "50,350",
    Action: "View Details Delete",
  },
];
