export const TenantSupportTicketsData = [
  {
    Ticket_ID: "#TKT0011",
    Tenant_Name: "Blue Chip Inc",
    Subject: "Mobile App Crash",
    Category: "Billing",
    Assigned_Agent: "Emily Davis",
    Agent_Image: "assets/img/profiles/avatar-06.jpg",
    Priority: "High",
    Created_Date: "29 Apr 2026",
    Status: "Open",
    Action: "Edit Delete View Details",
  },
  {
    Ticket_ID: "#TKT0012",
    Tenant_Name: "Titanium Media",
    Subject: "Subscription Renewal",
    Category: "Authentication",
    Assigned_Agent: "Sophia Martinez",
    Agent_Image: "assets/img/profiles/avatar-05.jpg",
    Priority: "Medium",
    Created_Date: "29 Apr 2026",
    Status: "Resloved",
    Action: "Edit Delete View Details",
  },
  {
    Ticket_ID: "#TKT0013",
    Tenant_Name: "Velocity Labs",
    Subject: "Data Export Issue",
    Category: "Billing",
    Assigned_Agent: "Marcus Wright",
    Agent_Image: "assets/img/profiles/avatar-04.jpg",
    Priority: "low",
    Created_Date: "28 Apr 2026",
    Status: "Open",
    Action: "Edit Delete View Details",
  },
  {
    Ticket_ID: "#TKT0014",
    Tenant_Name: "Zenith Corp",
    Subject: "Password Reset Help",
    Category: "Notifications",
    Assigned_Agent: "Isabella Cooper",
    Agent_Image: "assets/img/profiles/avatar-03.jpg",
    Priority: "Medium",
    Created_Date: "28 Apr 2026",
    Status: "Closed",
    Action: "Edit Delete View Details",
  },
  {
    Ticket_ID: "#TKT0015",
    Tenant_Name: "Eco-Stream",
    Subject: "Dashboard Not Loading",
    Category: "Performance",
    Assigned_Agent: "Emily Davis",
    Agent_Image: "assets/img/profiles/avatar-02.jpg",
    Priority: "High",
    Created_Date: "27 Apr 2026",
    Status: "Resloved",
    Action: "Edit Delete View Details",
  },
  {
    Ticket_ID: "#TKT0016",
    Tenant_Name: "Quantum Leap",
    Subject: "API Integration Fail",
    Category: "Billing",
    Assigned_Agent: "Robert Johnson",
    Agent_Image: "assets/img/profiles/avatar-01.jpg",
    Priority: "Medium",
    Created_Date: "17 Mar 2026",
    Status: "Open",
    Action: "Edit Delete View Details",
  },
  {
    Ticket_ID: "#TKT0017",
    Tenant_Name: "Alpha Solutions",
    Subject: "UI Bug Report",
    Category: "Notifications",
    Assigned_Agent: "Sophia Martinez",
    Agent_Image: "assets/img/profiles/avatar-17.jpg",
    Priority: "Medium",
    Created_Date: "25 Mar 2026",
    Status: "Closed",
    Action: "Edit Delete View Details",
  },
  {
    Ticket_ID: "#TKT0018",
    Tenant_Name: "Nebula Cloud",
    Subject: "Payment Timeout",
    Category: "Performance",
    Assigned_Agent: "Marcus Wright",
    Agent_Image: "assets/img/profiles/avatar-16.jpg",
    Priority: "low",
    Created_Date: "29 Mar 2026",
    Status: "Closed",
    Action: "Edit Delete View Details",
  },
  {
    Ticket_ID: "#TKT0019",
    Tenant_Name: "Veridian Systems",
    Subject: "Invoice Mismatch",
    Category: "Billing",
    Assigned_Agent: "Isabella Cooper",
    Agent_Image: "assets/img/profiles/avatar-15.jpg",
    Priority: "Medium",
    Created_Date: "03 Apr 2025",
    Status: "Open",
    Action: "Edit Delete View Details",
  },
  {
    Ticket_ID: "#TKT0020",
    Tenant_Name: "Sunburst Tech",
    Subject: "Login Access Error",
    Category: "Authentication",
    Assigned_Agent: "Robert Johnson",
    Agent_Image: "assets/img/profiles/avatar-14.jpg",
    Priority: "High",
    Created_Date: "25 Apr 2026",
    Status: "Resloved",
    Action: "Edit Delete View Details",
  },
];
